facebookresearch/fairchem

- ocpmodels/common/ase_utils.py
- ocpmodels/datasets/trajectory.py
- ocpmodels/trainers/forces_trainer.py
Compatible with trajectory and trajectory_lmdb datasets.
ML relaxation evaluator as is - updates to that will be in a future PR after we explore better alternatives.
> Resolves predict() bug cause form earlier commits

- ocpmodels/datasets/trajectory_lmdb.py
- ocpmodels/preprocessing/atoms_to_graphs.py
- scripts/parallel_preprocess_trajectories.py
[do not merge]
Tested with a small subset, works fine. Let me know if you have other thoughts.
> parallel preprocessing

- ocpmodels/datasets/trajectory_lmdb.py
@mshuaibii @weihua916 would be great if you could check if this fixes the LMDB memory issues with the latest data splits
> Opens connections to LMDB only when needed

- scripts/parallel_preprocess_trajectories.py
Structures are constructed such that surface is added first and then adsorbate added on top. Which means that we can recover the adsorbate indices by indexing backwards. The question remains of how many atoms are part of the adsorbate for a particular system. Based off the randomid and several mapping tables, that is recovered and extracted accordingly.
Considered adding all this to the `atoms_to_graph` script. That would require `randomid` to be fed such that they can be mapped accordingly.
> adds adsorbate flags to preprocessing

- ocpmodels/datasets/__init__.py
- ocpmodels/datasets/trajectory_lmdb.py
- ocpmodels/trainers/forces_trainer.py
- scripts/parallel_preprocess_trajectories.py
Samples N images per trajectory in constructing a batch
> Trajectory sampler batch loader

- ocpmodels/datasets/trajectory_lmdb.py
- tests/preprocessing/test_pbc.py
Resolves pbc bug caused by PyG's edge indexing when batching. Also updates the pbc test to test this specifically.
> resolves pbc bug caused by PyG batching

- configs/ocp_is2re/dimenet.yml
- ocpmodels/models/dimenet.py
Draft PR for now because I'm running sweeps to see if this works at least as well as reducing max no. of neighbors.
> Adds parameter for subsampling angles in DimeNet

- ocpmodels/trainers/dist_forces_trainer.py
> eval_every for ddp trainer

- ocpmodels/common/utils.py
Per @weihua916's request, the ability to filter neighbors on-the-fly. 
Getting the new pbc torch preprocessing in place would eliminate all this fyi.
> adds max neigh filter to pbc_distance()

- ocpmodels/common/meter.py
- ocpmodels/datasets/trajectory_lmdb.py
- ocpmodels/modules/evaluator.py
- ocpmodels/trainers/dist_forces_trainer.py
- ocpmodels/trainers/energy_trainer.py
- ocpmodels/trainers/forces_trainer.py
- tests/evaluator/test_evaluator.py
I've updated `EnergyTrainer` to make use of the new `Evaluator` and added some barebones tests. Will update `ForcesTrainer` soon.
> Adds a separate `Evaluator` class that trainers can import with a wider range of metrics

- ocpmodels/trainers/dist_forces_trainer.py
This prevents the Inf values in metrics that Muhammad has been seeing with DDP. 
In master, we were doing an AllReduce on the metrics in each iteration, which means that for each batch, the counts ("numel") and sum ("total") are updated to add up all of the previous values, which increased their values exponentially with DDP.
With this PR, we only apply AllReduce at the end of validation. This fixes the Inf bug and also speeds up validation quite a bit, because we only need one set of AllReduce calls for the entire val set.
> Fixed metric computation bug in DistributedForcesTrainer

- main.py
- ocpmodels/common/flags.py
Removes distributed flag - unused since #84. Let me know if this was used elsewhere.
> remove distributed flag

- main.py
- ocpmodels/common/distutils.py
- ocpmodels/common/flags.py
- ocpmodels/trainers/energy_trainer.py
- ocpmodels/trainers/forces_trainer.py
Allow training without distributed. Also adds back the `--distributed` option.
> Allow non-distributed training

- .circleci/config.yml
Added CI config, but I do not have permission to setup Circle CI on this repo. I've tested it on my own fork of the codebase.
> Added Circle CI config

- README.md
This PR has some minor changes to the README file, listed below: 
1. Removed a space before echo command in GPU machines sub-section
2. Updated and fixed an error in the Preprocess datasets sub-section
> minor changes to the README

- DATASET.md
This PR adds a DATASET.md file which has all the downloadable links. This is still work in progress as some of the links aren't up yet.
> Add dataset download page with links

- README.md
This PR updates the readme by including the "DATASET.md" link and project website separately.
> Update README with dataset page and project page

- .gitignore
- ocpmodels/common/relaxation/ml_relaxation.py
- ocpmodels/trainers/energy_trainer.py
- ocpmodels/trainers/forces_trainer.py
- scripts/preprocess_ef.py
- scripts/uncompress.py
Stores system id in prediction json to avoid index confusion for submission
Adds progress bar to preprocessing scripts
> stores system ids as keys for jsons

- DATASET.md
Adds download links for test sets.
> Add test sets for S2EF and IS2RE/IS2RS tasks

- ocpmodels/trainers/base_trainer.py
- ocpmodels/trainers/energy_trainer.py
- ocpmodels/trainers/forces_trainer.py
I'm working on a series of PRs to clean up and simplify the codebase. This is the first of these PRs.
Refactored trainer code by moving some of the common code from ForcesTrainer and EnergyTrainer to BaseTrainer.
> Refactored trainers

- ocpmodels/trainers/base_trainer.py
- ocpmodels/trainers/energy_trainer.py
- ocpmodels/trainers/forces_trainer.py
- A config that contains a test set no longer runs `validate()` but rather `predict()`, saving out predictions when validation metrics improve.
- Small bug fixes to #140 - converts list to numpy array before indexing
- Resolves ` VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences` when writing prediction files. (Forces are the ragged sequence) -> specifies numpy object
> validation not called on test set - fixes #139

- README.md
- models.md
This PR adds links for different pretrained models.
> Add pretrained models

- ocpmodels/common/relaxation/ase_utils.py
Updates OCP-ASE calculator to function after some of the latest `predict` changes.
> bugfix: ocp-ase calc support

- DATASET.md
This PR modifies the dataset.md file by adding a downloadable pickle file containing mapping information of OC20 datapoints.
> Add data-mapping pickle and update bibtex

- main.py
Still testing this out; followed https://github.com/facebookincubator/submitit/blob/master/docs/checkpointing.md.
> Adds support for auto-requeueing slurm jobs (after timeout / preemption)

- configs/s2ef/200k/forcenet/fn_forceonly.yml
- configs/s2ef/all/forcenet/fn_forceonly.yml
Since ForceNet was only trained on 200k here - moved accordingly.
> Moves ForceNet config to 200k

- docs/source/tutorials/train_s2ef_example.ipynb
Demo notebook update to function properly per recent changes to codebase. Issue #170
> Updates demo notebook per repo changes (#170)

- MODELS.md
> Clarify pretrained models docs (#174)

- ocpmodels/trainers/base_trainer.py
Addresses https://github.com/Open-Catalyst-Project/ocp/commit/9517d6a22b680dc1ab60a5822ebf4e59a9ea5e89#commitcomment-45808904. 
Resolves bug when trying to run `main.py` from outside repo directory.
cc - @wood-b can you confirm this on your end.
> log commit hash from outside repo

- ocpmodels/datasets/trajectory_lmdb.py
Minor issue raised by @wood-b -  LMDBs weren't closing properly for S2EF.
> closedb fix

- ocpmodels/datasets/trajectory_lmdb.py
- ocpmodels/trainers/base_trainer.py
- ocpmodels/trainers/forces_trainer.py
Resolves #192 
Wasn't able to test the relaxations portion of this, will update this PR when I get a chance. Forces variant works fine.
On the EvalAI side - to get the chunked versions we do something like this:
```
forces = file.forces
chunk_idx = file.chunk_idx
chunked_forces = np.split(forces, chunk_idx)
```
> NPZ object fix #192

- DATASET.md
- scripts/download_data.py
This PR does the following:
-  modifies the underlying downloads for all links.
- adds slab trajectories.
- data mapping information connecting adslab-slabs.
- checksums for all downloads
> Modify underlying downloads and add more download materials

- MODELS.md
This PR adds downloadable links corresponding to dimenet++ models.
> Add links to download trained dimenet++ models

- DATASET.md
Add extra information in the data mapping pkl.
> Modify data mapping pkl

- DATASET.md
- scripts/download_data.py
This PR adds download links for additional data that we generated via rattled relaxations and molecular dynamics simulations.
> Add rattled and MD downloads

- DATASET.md
- DATASET_PER_ADSORBATE.md
- DATASET_PER_ADSORBATE_IS2RES.md
> Add per adsorbate trajectories

- DATASET_PER_ADSORBATE.md
Link to `.extxyz` info in `DATASET_PER_ADSORBATE.md` was broken so I corrected it!
> fix extxyz ase link

- ocpmodels/common/relaxation/ase_utils.py
- ocpmodels/trainers/energy_trainer.py
> Accomodating use of OCPCalculator for energy calculations

- docs/source/tutorials/train_s2ef_example.ipynb
https://discuss.opencatalystproject.org/t/customised-dataset-attribute/95/5
Updates tutorial notebook to be compatible with v0.0.3 of the repo.
> updates s2ef notebook

- ocpmodels/models/dimenet.py
- ocpmodels/models/dimenet_plus_plus.py
This fixes the triplet indices in DimeNet and DimeNet++. Previously, they excluded triplets where the input and output node (i and k in i->j->k) are the same. This could lead to wrongly excluded edges since the node index of different periodic images of one atom would be the same. To fix this we now additionally check the `cell_offsets`.
> Fix DimeNet triplet indices

- TRAIN.md
- scripts/make_challenge_submission_file.py
Includes a script to make submissions for the NeurIPS 2021 Open Catalyst Challenge. All submissions are expected to be in a `.npz` file with the following format:
```
{
"challenge_ids": array(['0', '1', ...]),
"challenge_energy": array([-3.63920, -1.08237, 12.92103, ...,])
}
```
where both `challenge_ids` and `challenge_energy` are arrays of size 120000.
Examples:
IS2RE direct predictions
```
python main.py scripts/make_challenge_submission_file.py --path /path/to/is2re_predictions.npz --out-path neurips_2021_submission.npz
```
IS2RE relaxation predictions (1 S2EF model for relaxations and energy predictions)
```
python main.py scripts/make_challenge_submission_file.py --path /path/to/trajectory/data --out-path neurips_2021_submission_relax.npz --is2re-relaxations
```
IS2RE hybrid …
> challenge submission script

- ocpmodels/trainers/forces_trainer.py
Adds the ability to run relaxations and compute IS2RS / IS2RE metrics during S2EF training by passing the following flags:
```yaml
task:
...
eval_relaxations: True
num_relaxation_batches: 5 # optional; if skipped, will eval on full split
relaxation_steps: 300
write_pos: False
relax_dataset:
src: /path/to/val/id/data.lmdb
relax_opt:
name: lbfgs
maxstep: 0.04
memory: 50
damping: 1.0
alpha: 70.0
```
Corresponding metrics get logged to wandb / tensorboard as `f"{split}/{task}_{metric}"`, e.g. `val/is2re_energy_mae` or `val/is2rs_average_distance_within_threshold`.
Also changes the `num_relaxations` variable name to `num_relaxation_batches` to make it clearer.
> Evaluates relaxations and IS2R* metrics during S2EF training

- DATASET.md
> swap checksums

- ocpmodels/common/relaxation/ase_utils.py
Updates OCPCalculator to :
1.  Construct graph by default
2.  Works with a dictionary of config
> OCPCalc Update: uses otf_graph by default and takes in dictionary as well

- README.md
- env.common.yml
- env.cpu.yml
- env.gpu.yml
Repo is compatible with PyTorch 1.9.0, updates installation details accordingly.
> PyTorch 1.9.0

- ocpmodels/common/relaxation/ase_utils.py
Addresses #331 
```
calc = OCPCalculator(checkpoint=/path/to/checkpoint.pt, device=0)
atoms.set_calculator(calc)
energy = atoms.get_potential_energy()
```
> OCPCalculator CUDA support

- .circleci/config.yml
- ocpmodels/models/painn/painn.py
> Fixes PaiNN's stability issues

- ocpmodels/common/relaxation/ase_utils.py
> Make `OCPCalculator` support both list and dict dataset configs

- ocpmodels/preprocessing/atoms_to_graphs.py
> Set tags in `AtomsToGraphs` since GemNet models need it for inference

- ocpmodels/common/registry.py
This PR updates the registry `get_class` function to provide more reliable errors when we fail to find a valid import.
Example error:
```
(ocp-prs) nimashoghi ~/updated_ocp/09_06 better-import-errors
λ python main.py --mode train --config-yml configs/s2ef/200k/cgcnn/cgcnn.yml
amp: false
cmd:
checkpoint_dir: ./checkpoints/2022-09-06-11-03-44
commit: 85cd7b5
identifier: ''
logs_dir: ./logs/tensorboard/2022-09-06-11-03-44
print_every: 10
results_dir: ./results/2022-09-06-11-03-44
seed: 0
timestamp_id: 2022-09-06-11-03-44
dataset:
grad_target_mean: 0.0
grad_target_std: 2.887317180633545
normalize_labels: true
src: /datasets01/open_catalyst/oc20/082422/struct_to_energy_forces/train/200k
target_mean: -0.7554450631141663
target_std: 2.887317180633545
gpus: 1
logger: tensorboard
model: …
```
> Added better/more legible registry import errors

- tests/models/test_gemnet_oc.py
A few unit tests for GemNet-OC -- rotation in/equivariance, shapes, and outputs from pretrained weights
> Unit test for GemNet-OC

- ocpmodels/common/registry.py
This should fix #408.
Thanks @AdeeshKolluru for the catch!
> Remove Python 3.8 only fstring interpolations

- MODELS.md
- configs/oc22/s2ef/gemnet-oc/gemnet_oc.yml
- configs/oc22/s2ef/gemnet-oc/gemnet_oc_finetune.yml
- configs/oc22/s2ef/gemnet-oc/gemnet_oc_oc20_oc22.yml
Releases the best S2EF OC22 model configs and checkpoints.
> OC22 pretrained models

- configs/s2ef/example.yml
- ocpmodels/common/utils.py
- ocpmodels/models/gemnet_oc/gemnet_oc.py
- ocpmodels/models/gemnet_oc/layers/atom_update_block.py
- ocpmodels/trainers/forces_trainer.py
Uses [torch.use_deterministic_algorithms](https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms).
> Use "deterministic" scatter on CUDA tensors if implemented

- tutorials/data_preprocessing.ipynb
> fix tag description

- ocpmodels/datasets/lmdb_dataset.py
- ocpmodels/datasets/oc22_lmdb_dataset.py
Reverts Open-Catalyst-Project/ocp#476
> Revert "LMDB folder fix"

- .github/workflows/stale.yml
- env.common.yml
- Updates ase to 3.22.1, pymatgen to 2023.5.10
- Adds a github action to close inactive issues and PRs
> Maintenance updates

- .github/workflows/stale.yml
- env.common.yml
* Version bump for ase, pymatgen
* Gh action for closing inactive issues and PRs
> Maintenance updates (#506)

- ocpmodels/models/escn/escn.py
https://github.com/Open-Catalyst-Project/ocp/pull/465 resolved model initialization but didn't resolve an additional error in the forward pass with mismatch devices. This resolves it.
> eSCN cpu fix

- ocpmodels/models/equiformer_v2/equiformer_v2_oc20.py
Following #467, adds an `enforce_max_neighbors_strictly` flag to EquiformerV2.
> Adds boolean for whether to use strict max_neighbors in EquiformerV2

- .circleci/config.yml
- codecov.yml
- ocpmodels/common/relaxation/ase_utils.py
This is a fix for #583, which was happening because the ASE calculator interface wasn't loading nested config dictionaries correctly.
> Fixes nested YAML config loading from the ASE calculator

- ocpmodels/datasets/ase_datasets.py
Intended to fix this issue: https://discuss.opencatalystproject.org/t/pretrained-ocp-models/348/8
> Add natoms to ASE datasets

- .circleci/config.yml
- ocpmodels/common/relaxation/ase_utils.py
- ocpmodels/trainers/base_trainer.py
- tests/common/__snapshots__/test_ase_calculator.ambr
- tests/common/test_ase_calculator.py
> add seed option for calculator

- ocpmodels/common/data_parallel.py
- ocpmodels/trainers/ocp_trainer.py
See issue https://github.com/Open-Catalyst-Project/ocp/issues/641 for discussion
> Add warning and optimize sampler per @lbluque suggestion

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/test-release.yml
data-oc and demo-ocpapi had the wrong  artifact download path
> fix dist paths in release workflow

- docs/_toc.yml
- docs/core/datasets/oc20dense.md
- docs/core/datasets/oc20neb.md
per Zack's request I am adding some md files to populate the website with additional dataset pages for OC20dense and OC20NEB
> adding pages for oc20dense and oc20neb

- docs/_config.yml
- docs/core/install.md
- docs/index.md
- docs/tutorials/cattsunami_walkthrough.md
Update the install instructions 
- Three sections (env install, no code install, development install)
- Add wget to conda env code blocks
> update install instructions

- src/fairchem/core/common/logger.py
- src/fairchem/core/trainers/base_trainer.py
Log num params to W&B, will useful for scaling law/model size comparisons
Example:
https://fairwandb.org/rgao/fairchem/runs/2024-06-25-22-51-44-main_test/overview
> Log num params to W&B

- README.md
- docs/index.md
* Fix broken `deploy_docs` badge on the README page
* Add a "open in codespaces" link in the website and readme for fast start for people interested in trying the models / tutorial pages!
> fix docs badge, and add codespaces badge

- docs/core/install.md
List the available fairchem packages explicitly so people know which are available to install
Show example of when to use pytest (after core[dev] install)
> list available fairchem packages; and show how to use pytest in [dev]

- src/fairchem/core/models/escn/escn.py
Similar to this we need the mean energy for escn as well:
https://github.com/FAIR-Chem/fairchem/pull/818
> Add mean e to escn energy head

- src/fairchem/data/oc/core/interface_config.py
- src/fairchem/data/oc/core/slab.py
- src/fairchem/data/oc/utils/vasp.py
- src/fairchem/data/oc/utils/vasp_flags.py
`from_bulk_get_random_slab` was ignoring `min_ab` in its useage. 
Add support for different pp setups.
> add tags, fix min_ab slab

- src/fairchem/applications/cattsunami/tutorial/adding_a_rxn_to_the_db.ipynb
Adding a tutorial for how to make custom reaction entries.
> adding tutorial

- docs/core/datasets/oc20.md
> add per adsorbate download links

- src/fairchem/core/_cli_hydra.py
- src/fairchem/core/modules/scheduler.py
- tests/core/test_hydra_cli.py
- move Cosine Lambda function to LRScheduler (instead of using the eqv2 one)
- add minor shortcut key for hydra cli (use -c, --config now)
- fix logging in hydra cli
> Add cosine LR, minor edit to hydra cli

- src/fairchem/core/common/profiler_utils.py
Add a torchTNT callback to enable the profiler
> Add profiler callback

- src/fairchem/core/common/profiler_utils.py
- src/fairchem/core/preprocessing/atoms_to_graphs.py
- tests/core/preprocessing/test_atoms_to_graphs.py
Optionally create a molecule box around an ASE atoms that doesn't have a cell.
> Add molecule cell to a2g

- src/fairchem/core/_cli_hydra.py
- src/fairchem/core/common/utils.py
- src/fairchem/core/datasets/base_dataset.py
Add the cluster name to the config metadata to be able to identify which cluster the job was run on
> [cli_hydra] Add cluster name to metadata

- src/fairchem/core/_cli_hydra.py
- src/fairchem/core/common/utils.py
* Add results dir field to save predictions/metrics
* Minor change to tensor_stats to get items on cpu
> Add results dir for saving full predictions/metrics

- docs/core/datasets/oc20.md
> add split info to metadata

- .github/workflows/build_docs.yml
- .github/workflows/deploy_docs.yml
- packages/fairchem-core/pyproject.toml
Since we have a secret in our workflow, we need a small tweak to make sure the sub workflow in the docs deployment inherits the secret. 
Also small tweak to fix a repeated TQDM warning about ipywidgets in the docs.
> fix doc deployment

- src/fairchem/core/common/gp_utils.py
- tests/core/common/test_gp_utils.py
- tests/core/e2e/test_s2ef.py
This PR adds a new graph parallel function GatherFromModelParallelRegionSumGrad that is required to get parity with non graph parallel implementation. 
Additionally this PR adds gradient tests comparing graph parallel to non-graph parallel and tests comparing graph parallel to analytic outputs.
> Graph parallel fix and tests

- src/fairchem/core/_cli_hydra.py
only initialize logger once when using job arrays
> Only initialize logger once

- src/fairchem/core/_cli_hydra.py
Only run a reduce job if all run jobs complete successfully
> afterok all run job array jobs

- .github/release-drafter-applications_cattsunami.yml
- .github/release-drafter-core.yml
- .github/release-drafter-data_oc.yml
- .github/release-drafter-demo_ocpapi.yml
- .github/workflows/label_checker.yml
Add no-op for things like documentation, testsm, or non breaking code reorganizing
> update PR label checking

- docs/dac/examples_tutorials/adsorption_energy.md
Small fix with the ODAC tutorial to print the final outputs.
> odac tutorial small fix

- docs/_toc.yml
- docs/catalysts/examples_tutorials/OCP-introduction.md
- docs/catalysts/examples_tutorials/adsorbml_walkthrough.md
- docs/catalysts/examples_tutorials/adsorption_energies/adsorption_energies.md
- docs/catalysts/examples_tutorials/cattsunami_tutorial.md
- docs/catalysts/examples_tutorials/ocpapi.md
- docs/core/common_tasks/ase_calculator.md
- docs/core/common_tasks/batch_inference.md
- docs/core/quickstart.md
- docs/dac/examples_tutorials/adsorption_energy.md
- docs/index.md
- docs/inorganic_materials/examples_tutorials/bulk_stability.md
- docs/inorganic_materials/examples_tutorials/elastic.md
- docs/inorganic_materials/examples_tutorials/phonons.md
* fix broken link in docs toc
* update code->code-cell in the docs to avoid warnings
> Fix docs toc

- src/fairchem/core/datasets/atomic_data.py
- tests/core/datasets/test_atomic_data.py
PR for https://github.com/facebookresearch/fairchem/pull/1310
* Fix atomicdata conversion bug
* Add a unit test
---------
> Fix a bug in AtomicData.to_ase_single (#1310)

- .github/actions/multi-trigger-cleanup/action.yml
- .github/actions/multi-trigger-setup/action.yml
- .github/workflows/build_docs.yml
- .github/workflows/test.yml
Adds a workflow_run trigger for running tests and building docs. This will run after the workflow added in #1349 finishes.
> Trigger tests and build_docs on contributor check

- .github/workflows/build.yml
- .github/workflows/release-drafter-data-omol.yml
- .github/workflows/release-drafter-data_omol.yml
- .github/workflows/release.yml
- .github/workflows/test-release.yml
- packages/fairchem-data-omol/pyproject.toml
Add workflows to version and release `fairchem.data.omol` to PyPI
1. Add release drafter config and workflow
2. Add fairchem-data-omol to release workflow
> Add release workflows for fairchem-data-omol

- .github/workflows/build_docs.yml
- .github/workflows/test.yml
Add merge_group triggers to re-enable merge queue.
Status checks included:
- tests
- lint
- build docs
> add merge_group triggers

- packages/fairchem-core/pyproject.toml
fixed https://github.com/facebookresearch/clusterscope/issues/56 on `clusterscope` version `0.0.12`
ci
> upgrade clusterscope

- packages/fairchem-core/pyproject.toml
one-line change to remove support for python 3.9
> bump python version to 3.10
