ocpmodels/datasets/gasdb.py

`neighbors` is a list of 3-tuples but was getting zipped and assigned to 4 separate lists.
This was causing neighbor indices and distances to be assigned default dummy values.

Fixes silently failing ValueError when zipping atom neighbor features

---

ocpmodels/common/logger.py
ocpmodels/datasets/gasdb.py
ocpmodels/trainers/sktrainer.py

Wraps up some of the overhead of folder/config management. Now we can pass all the arguments as a dictionary instead of a yaml. It also adds a `.predict` method to the trainer so we can pass in new data to predict on. Here's an example of the usage:
```
from ocpmodels.trainers.sktrainer import SKTrainer
task = {'dataset': 'gasdb',
'description': 'Binding energy regression on a dataset of DFT results for CO, H, N, O, and OH adsorption on various slabs.',
'labels': ['binding energy'],
'metric': 'mae',
'type': 'regression'}
model = {'name': 'cgcnn',
'atom_embedding_size': 64,
'fc_feat_size': 128,
'num_fc_layers': 4,
'num_graph_conv_layers': 6}
dataset = {'src': 'path_to_src',
'train_size': 640,
'val_size': 160,
'test_size': 200}
optimizer = {'batch_size': 64,
'lr_gamma': 0.1,
'lr_initial': …
```

Implement an SKLearn-like trainer

---

README.md
env.common.yml
env.cpu.yml
env.extras.yml
env.gpu.yml

Common dependencies were split out of `env.cpu.yml` into `env.common.yml`. GPU specific dependencies were put into `env.gpu.yml`. This allows the user to use `conda-merge` to create a final config which can be passed to `conda env create`, e.g.
```
conda-merge env.common.yml env.cpu.yml > env.yml
conda env create -f env.yml
```
Followed the updated instructions for testing to make sure envs were created without error

Create environment files for GPU dependencies

---

ocpmodels/common/ase_calc.py
ocpmodels/datasets/co_cu_md.py
ocpmodels/trainers/base_trainer.py
ocpmodels/trainers/md_trainer.py

Speeds things up by a bit. A 300-step relaxation with CGCNN now takes about ~30 seconds compared to ~50 seconds earlier.

Converts ase atoms to batches without writing intermediate traj files during inference

---

.gitignore
configs/2020_07_13_ocp_reset_200k/schnet_sweep.yml
env.common.yml
main.py
ocpmodels/common/flags.py
ocpmodels/common/utils.py

The main.py script still works like before for local training. 
To train on the cluster, just add a `--submit`, for example:
```
python main.py --config-yml configs/2020_07_13_ocp_reset_200k/schnet.yml --seed 1 --submit
```
It is also possible to run a grid search by specifying the `--sweep-yml` argument:
```
python main.py --config-yml configs/2020_07_13_ocp_reset_200k/schnet.yml --seed 1 --submit --sweep-yml configs/2020_07_13_ocp_reset_200k/schnet_sweep.yml
```

Added submitit support to run on slurm cluster

---

ocpmodels/common/ase_utils.py
ocpmodels/common/utils.py
ocpmodels/datasets/trajectory_lmdb.py
ocpmodels/preprocessing/atoms_to_graphs.py
scripts/parallel_preprocess_trajectories.py
tests/models/test_cgcnn.py
tests/models/test_dimenet.py
tests/models/test_schnet.py
tests/preprocessing/test_atoms_to_graphs.py
tests/preprocessing/test_pbc.py

@wood-b @abhshkdz and I didn't find a need for dummy indices. We were actually deleting them downstream in our dataloaders/they were causing us issues in the pbc implementation. Let us know if there was a reason to have them at all, otherwise this PR returns them in variable neighbor lengths which isn't a problem for PyG.
@abhshkdz Thoughts on breaking this PR into 2? This current PR would lead to old datasets being inaccurate in their training schemes (with pbc). We can merge this for preprocess refactor until I generate a new batch and then add the dataloader/pbc calculation bits.

preprocessing refactor: removes dummy indices, resolves pbc distance bug, cleans up pbc/dataloader utils.

---

configs/ocp_s2ef/dimenet.yml
ocpmodels/models/dimenet.py

The [pytorch geometric implementation](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/models/dimenet.py#L445) looks incorrect to me.
For a triplet from `i` to `j` to `k`, the two vectors we should be considering when computing angles are `i—>j` and `j—>k` and not `i—>j` and `i—>k`. Let me know if that doesn't make sense.

Fixes bug in computing angles in DimeNet

---

configs/ocp_is2re/dimenetplusplus.yml
configs/ocp_s2ef/dimenet.yml
configs/ocp_s2ef/dimenetplusplus.yml
ocpmodels/models/__init__.py
ocpmodels/models/dimenet_plus_plus.py

This is based on the official tensorflow release: https://github.com/klicperajo/dimenet
The primary differences are in the `InteractionBlock`s (replacing the bilinear layer with a Hadamard product + fully-connected layers) and `OutputBlock`s.
I don't have a training / inference speed comparison between DimeNet and DimeNet++ at same model capacity yet, but was able to fit training batch sizes of 48 and 24 for IS2RE and S2EF respectively with DimeNet++ on 2 GPUs.

Implements DimeNet++

---

configs/ocp_is2rs/base.yml
main.py
ocpmodels/trainers/energy_trainer.py
ocpmodels/trainers/forces_trainer.py
scripts/make_evalai_json.py
scripts/merge_pos_evalai.py
train.md

Modifies the prediction files created by `.predict()` call in a format compatible with json. Because prediction files are created independently, a separate script is included to join the separate files to be submitted to evalAI directly.

save prediction files in format for evalAI

---

ocpmodels/common/relaxation/ml_relaxation.py
ocpmodels/trainers/forces_trainer.py

nit - ml relaxation scripts aren't performing "eval" anymore, renamed accordingly.

more consistent naming

---

ocpmodels/trainers/energy_trainer.py

`predict` call did not check if `normalizer` was first available.

resolves bug in energy trainer predict

---

ocpmodels/trainers/energy_trainer.py
ocpmodels/trainers/forces_trainer.py

Energy trainer tries to checkpoint val metrics when val set not specified. Checkpoints every training epoch if no val set is found. We could also just throw an error message saying please specify val set.

BUGFIX: broken trainer when val set not specified

---

ocpmodels/common/data_parallel.py
ocpmodels/datasets/trajectory_lmdb.py
ocpmodels/models/cgcnn.py
ocpmodels/models/dimenet.py
ocpmodels/models/schnet.py
ocpmodels/trainers/energy_trainer.py
ocpmodels/trainers/forces_trainer.py

Resolves codebase errors when trying to train with an LMDB without edge information. Let's merge this into #91 before `release`

otf support for LMDBs w/o edge information

---

scripts/preprocess_ef.py

Resolves small bug in chunking when `num_workers` is not divisible into total # of txt files.

resolves uneven chunking

---

ocpmodels/trainers/forces_trainer.py

Relaxation loader uses single-point-lmdb dataset, which requires a distributed sampler.

adds sampler to relaxation loader

---

train.md

Commas lead to the accompanying values to be read as strings, fixes in train.md documentation

removes commas from config example

---

ocpmodels/trainers/base_trainer.py

Reverts use of `Path` object to string for easier log parsing. Currently looks like:
```
checkpoint_dir: !!python/object/apply:pathlib.PosixPath
- checkpoints
- 2020-10-26-14-19-34
identifier: ''
logs_dir: !!python/object/apply:pathlib.PosixPath
- logs
- tensorboard
- 2020-10-26-14-19-34
print_every: 10
results_dir: !!python/object/apply:pathlib.PosixPath
```
Changed to:
```
checkpoint_dir: ./checkpoints/2020-10-26-14-19-34
identifier: ''
logs_dir: ./logs/tensorboard/2020-10-26-14-19-34
print_every: 10
results_dir: ./results/2020-10-26-14-19-34
```
We could also call `str()` in front of these lines if we wanted to stick with `Path` https://github.com/Open-Catalyst-Project/ocp/blob/d422307b65bb5e2bd27df60244391570398fa0ae/ocpmodels/trainers/base_trainer.py#L79-L81 Both lead to the same …

reverts Path to string

---

ocpmodels/common/distutils.py
ocpmodels/trainers/base_trainer.py

Saving predictions in multi-GPU implementations risks hitting an edge case of GPU timestamps being not identical. Resolves this issue by making sure all ranks use the master rank timestamp.

all ranks use master rank timestamps/directories

---

env.cpu.yml
env.gpu.yml

Pytorch Geometric has moved around their installation binaries, breaking our existing installation files. Updates accordingly.
Our build tests weren't catching this because it had the environment cached.

updates PyG installation binaries

---

ocpmodels/datasets/single_point_lmdb.py
ocpmodels/datasets/trajectory_lmdb.py
ocpmodels/trainers/energy_trainer.py
ocpmodels/trainers/forces_trainer.py

Some LMDB optimizations following discussions/guidance from the following. Mainly leaving the lmdb open after each get item call.
https://github.com/pytorch/vision/blob/4076a54a67e0d0be94352a3360e364c63677a8ec/torchvision/datasets/lsun.py#L22-L23
https://discuss.pytorch.org/t/whats-the-best-way-to-load-large-data/2977/

LMDB optimizations

---

ocpmodels/trainers/base_trainer.py

This fix allows the use of alternative TensorBoard SummaryWriter's (e.g., GFile, S3, etc). Using `pathlib.Path`, it changes incoming `--run-dir=s3://path` to `s3:/path` (Note the single slash) and the `SummaryWriter` check fails to match due to the single slash.
The fix is to not wrap in a `pathlib.Path` and do inline concatenation using os.path.join
_(Note too that to use tensorboard logging to s3 you have to include `boto3` as a dependency)_
- [0] https://github.com/tensorflow/tensorboard/blob/master/tensorboard/compat/tensorflow_stub/io/gfile.py#L224
- [1] https://github.com/tensorflow/tensorboard/blob/master/tensorboard/compat/tensorflow_stub/io/gfile.py#L38

Fix run_dir handling

---

main.py
ocpmodels/common/flags.py
ocpmodels/common/utils.py

Overriding configs from command line is currently structured as:
`python main.py ... ... --config-override '{"model":{"num_layers": 3, "hidden_channels":128, ...}}'`
This structure, however, makes integrating with HPO tools a challenge as they often feed in arguments as:
`python main.py ... ... --num_layers=3 --hidden_channels=128 ...`
This PR allows model hyperparameters to be overridden directly in the above format. `config-override` is left as part of this PR unless we think we can safely remove. One notable difference is `config-override` allows you to specify new arguments not already contained in the yaml configs, while the changes here can only modify existing parameters defined in the yaml configs.
As an example, this PR specifically allows the use of wandb's HPO: …

update config override

---

configs/s2ef/all/forcenet/fn_forceonly.yml

Addresses issue #167: Forcenet config stored in `configs/s2ef/all` but reads 200k set instead of all. Updates accordingly.

Forcenet config fix

---

ocpmodels/trainers/base_trainer.py

Logs commit # and no. of gpus used for training (this isn't easily identified by looking at a config)
Sample output - note `commit` and `gpus`
```
amp: false
cmd:
checkpoint_dir: ./checkpoints/2021-01-06-22-56-00
commit: 4b00139
identifier: ''
logs_dir: ./logs/tensorboard/2021-01-06-22-56-00
print_every: 10
results_dir: ./results/2021-01-06-22-56-00
seed: 0
timestamp: 2021-01-06-22-56-00
dataset:
grad_target_mean: 0.0
grad_target_std: 2.887317180633545
normalize_labels: true
src: data/s2ef/200k/train/
target_mean: -0.7554450631141663
target_std: 2.887317180633545
gpus: 2
logger: tensorboard
model: schnet
model_attributes:
cutoff: 6.0
hidden_channels: 1024
num_filters: 256
num_gaussians: 200
num_interactions: 3
use_pbc: true
optim:
batch_size: 32
eval_batch_size: 16
force_coefficient: 100 …
```

Log git commit and no. of gpus used for better debugging

---

ocpmodels/preprocessing/atoms_to_graphs.py

Users generating LMDBs with data that does not have fixed atoms defined are unable to with existing preprocessing script. Resolves that issue.

catch for no fixed atoms

---

ocpmodels/datasets/trajectory_lmdb.py

In case of unequally-sized LMDBs (our recently updated LMDBs), different processes have different no. of samples leading to issues with DDP.
This fix reads the length of each LMDB to set the no. of samples for each process. Processes with fewer samples are padded till `replica_size`.

Bugfix: pad dataset to ensure all dataloader processes have equal samples

---

ocpmodels/models/cgcnn.py
ocpmodels/models/dimenet.py
ocpmodels/models/dimenet_plus_plus.py
ocpmodels/models/schnet.py
ocpmodels/trainers/base_trainer.py
ocpmodels/trainers/energy_trainer.py
ocpmodels/trainers/forces_trainer.py

Validation memory usage is higher than that of training. This PR resolves this issue. 
Using the same dataset for train/val with `shuffle=False`, I benchmarked 10 updates of train/val respectively (allocated in MB):
Pre-Fix:
```
allocated 3324.904448
allocated 4519.053312
allocated 2300.791808
allocated 2240.774144
allocated 4299.392
allocated 3382.70976
allocated 4030.028288
allocated 4143.101952
allocated 3183.919616
allocated 3353.640448
allocated 6638.859776
allocated 7822.145024
allocated 6824.054784
allocated 4529.233408
allocated 6493.454848
allocated 7634.866176
allocated 7393.4976
allocated 8142.780416
allocated 7296.930304
forcesx_mae 0.07260803263042843
forcesy_mae 0.07774501425125371
forcesz_mae 0.0779459377799158
forces_mae 0.07609966071247863
forces_cos 0.018825592618360327 …
```

Resolves validation gpu memory issue

---

ocpmodels/common/utils.py
ocpmodels/models/cgcnn.py
ocpmodels/models/dimenet.py
ocpmodels/models/dimenet_plus_plus.py
ocpmodels/models/schnet.py

Small optimization to #199 - Previous PR always had `torch.enable_grad()` for the forward pass, even for models making only energy predictions...which was unnecessary. This PR defines a custom decorator to switch between the two settings depending on whether forces are being regressed or not. 
Profiling GPU usage (MB) for energy predictions:
PR #199:
```
allocated 2474.7626953125
allocated 1377.052734375
allocated 2080.26708984375
allocated 1914.98486328125
allocated 1480.64892578125
allocated 1414.263671875
allocated 1962.06591796875
allocated 1587.49658203125
allocated 1823.33203125
allocated 2392.71630859375
allocated 2108.71044921875
allocated 1719.5595703125
allocated 1435.11962890625
allocated 1764.458984375
allocated 1667.7919921875
allocated 1408.41943359375
allocated …
```

conditional decorator for energy/force trainers

---

main.py
ocpmodels/common/flags.py
ocpmodels/common/utils.py

Follow up to - https://github.com/Open-Catalyst-Project/ocp/issues/174.
Includes a flag to make this easily modified without having people change the source code.
To load our DDP pretrained checkpoints with only 1 GPU:
`python main.py --mode ... --config-yml ... --checkpoint ... --nonddp`

flag to load ddp cp without ddp

---

.circleci/config.yml
README.md
env.common.yml
env.cpu.yml
env.gpu.yml
setup.py

Still testing this out.
- Upgraded to pytorch 1.7.1, pytorch-geometric 1.6.3
- Dropped `gpytorch` as a dependency since we no longer use it in `master`. Can add it back if we use it in future.
- Upgraded `ase` to 3.21.* and `pymatgen` to 2021.12.31

Upgrades to pytorch 1.7.1, pytorch-geometric 1.6.3

---

ocpmodels/trainers/base_trainer.py

Allows for optimizer+optimizer params to be defined at the config level. Still defaults to `AdamW`.
Necessary for replicating alternative models' performance with different optimizer. A future PR will also customize schedulers as well.

Optimizer flexibility 

---

tests/models/test_dimenet.py
tests/models/test_dimenetpp.py
tests/models/test_schnet.py

Makes CI tests deterministic - preventing the need to restart a test with a failing bad seed (e.g. https://app.circleci.com/pipelines/github/Open-Catalyst-Project/ocp/452/workflows/449c0c03-38fc-4d4d-a550-98e17f0aa642/jobs/500).
Also adds DimeNet++ for completeness.

Deterministic CI tests

---

ocpmodels/modules/scheduler.py
ocpmodels/trainers/base_trainer.py

This is part two of #232
Implementation of a null scheduler for constant learning rate:
- no torch.optim.lr_scheduler is instantiated
- on scheduler.step() nothing happens
- logic is added so the scheduler.state_dict() is not saved or loaded 
Features:
- ability to run without a learning rate scheduler — one use case is population based training with Ray Tune

Add null scheduler

---

ocpmodels/modules/scheduler.py

Resolves a bug when an alternative optimizer is defined in the config:
```
File "/home/jovyan/projects/ocp/ocpmodels/modules/scheduler.py", line 35, in __init__
self.scheduler = self.scheduler(optimizer, **scheduler_args)
TypeError: __init__() got multiple values for argument 'optimizer'
```
Example config - 
```
optim:
batch_size: 32
eval_batch_size: 16
num_workers: 64
optimizer: Adam
optimizer_params: {"amsgrad": True}
lr_initial: 0.0005
scheduler: ReduceLROnPlateau
mode: min
factor: 0.8
patience: 10
max_epochs: 30
force_coefficient: 100
```

Scheduler bugfix

---

ocpmodels/trainers/base_trainer.py
ocpmodels/trainers/energy_trainer.py
ocpmodels/trainers/forces_trainer.py
scripts/hpo/README.md
scripts/hpo/run_tune_pbt.py

This is part three of #232.
Adds the ability to checkpoint with Ray Tune, enabling methods such as population based training. The hpo documentation was updated accordingly.
Notes:
- I added a [save_state](https://github.com/Open-Catalyst-Project/ocp/blob/hpo_checkpointing/ocpmodels/trainers/base_trainer.py#L424) function to the base trainer to minimize duplicate code between the `save` and `save_hpo` functions 
- I added a [variable](https://github.com/Open-Catalyst-Project/ocp/blob/hpo_checkpointing/ocpmodels/trainers/base_trainer.py#L150) in the optim section of the config `checkpoint_every`. This allows for control of the HPO checkpointing frequency instead of just on or off. For the moment, I put the variable in the optim section, but could create an HPO section — seemed unnecessary …

Adds checkpointing functionality for Ray Tune

---

main.py

In order to use submitit with OCP at NERSC additional slurm parameters are required. For example adding a `constraint` or adding an `account`.
This PR allows for additional slurm arguments through a slurm section of the yaml config. I thought it would be better in the config than adding a bunch of command line arguments. Below is an example slurm section:
```
slurm:
account: n1111
qos: special
partition: null
constraint: gpu
time: 10
``` 
Features:
- Ability to add or overwrite submitit slurm parameters with `slurm_additional_parameters` dict

Adds additional slurm parameters for submitit

---

.pre-commit-config.yaml
env.common.yml
env.cpu.yml
env.gpu.yml
ocpmodels/trainers/base_trainer.py

Updates repo and corresponding dependencies for Pytorch 1.8, Python 3.8.
~~SchNet on this version of torch_geometric currently breaks, I have raised the issue in their repo https://github.com/rusty1s/pytorch_geometric/issues/2708. @abhshkdz if you think of a work around let me know, we'll have to wait for that before we merge this.~~ They've pushed a fixed.
Note - I've dropped the CUDA version to 10.2, torch_geometric and pytorch have binaries for 10.2 and 11.1, not 11.0.

Pytorch 1.8.1, Python 3.8 Support

---

README.md
ocpmodels/datasets/trajectory_lmdb.py
ocpmodels/trainers/forces_trainer.py

Rather than splitting LMDBs across all processes, split all data across all processes to avoid issues when # of GPUs are much larger than # of LMDBs. Allows us to leverage the DistributedSampler instead of writing our own custom partitioning scheme. 
I benchmark timings of SchNet-200k for 10 epochs on 4 nodes, 32 effective GPUs (NOTE - nodes here were not controlled, which could explain the variability in training times):
```
train
Old:  918.3643939495087
New: 1105.6444401741028
pred
Old: 273.68402218818665
New: 225.97153663635254
```
To control for system differences, I ran things locally on 2 GPUs for a single epoch:
```
train
Old: 663.723126411438s
New: 662.4184503555298
```

#GPUs>#LMDBs bugfix

---

TRAIN.md
configs/s2ef/2M/dimenet_plus_plus/dpp_relax.yml
scripts/make_submission_file.py
scripts/preprocess_relaxed.py

Following the updates found [here](https://discuss.opencatalystproject.org/t/is2re-table-4-corrections/59), this PR includes and updates scripts to allow for IS2RE relaxation approaches via the 2 approaches discussed in the linked table:
1. Train an S2EF model (energy+forces), run ML relaxations (saving out trajectories), create submission files via trajectory files.
2. Train 2 S2EF models, a force-only and an energy-only model. Run ML relaxations (saving out trajectories) via the force-only model, create LMDB files from the generated trajectories, make predictions via the energy-only model.
- Modifies https://github.com/Open-Catalyst-Project/ocp/blob/master/scripts/make_submission_file.py to take in command line arguments. Includes additional methods to create submission files for IS2RE …

IS2RE relaxation scripts

---

ocpmodels/common/utils.py

Looks for an `experimental/.ignore` file and removes those paths from being imported.
Example `.ignore`:
```
abc
def
```
would ignore `experimental/abc/*py`, `experimental/def/*py`.

Support for ignoring specified directories within `experimental`

---

ocpmodels/trainers/energy_trainer.py

Re  #260 - Post-merge change: `validate` no longer takes `epoch` as an argument. This was resolved for `forces_trainer` but not `energy_trainer`.

bugfix: remove epoch arg from validate

---

ocpmodels/models/gemnet/fit_scaling.py

The model name in gemnet fit_scaling.py needed to be updated to reflect the different variants i.e. `gemnet_t`. Also, when I ran black on the file is switched the order of imports — not sure if people are using different versions of black but I did not push the changes to imports.

bugfix: update model name in gemnet fit_scaling

---

tests/evaluator/test_evaluator.py

This test can fail randomly since the difference is sometimes too large.

Reduce test_cosine_similarity check to 2 decimals

---

env.common.yml
ocpmodels/common/hpo_utils.py
ocpmodels/common/utils.py
ocpmodels/trainers/base_trainer.py
scripts/hpo/README.md

This PR makes Ray Tune an optional dependency and fixes the checkpointing bug caused by importing Ray (only an issue for those using submitit). More details on the checkpointing bug can be found [here](https://github.com/ray-project/ray/issues/17745).

Makes Ray Tune optional and fixes submitit checkpointing bug

---

env.common.yml
main.py
ocpmodels/common/data_parallel.py
ocpmodels/common/flags.py
ocpmodels/datasets/single_point_lmdb.py
ocpmodels/datasets/trajectory_lmdb.py
ocpmodels/trainers/base_trainer.py
ocpmodels/trainers/energy_trainer.py
ocpmodels/trainers/forces_trainer.py

This PR implements a simple load balancing algorithm inside the batch sampler. The new `BalancedBatchSampler` either balances by number of atoms or by number of neighbors. Load balancing is activated by default (in atoms mode). Balancing relies on metadata stored alongside the lmdbs. If the `metadata.npz` file is not found, we print a warning. It is then deactivated per default. However, if the user explicitly specifies a load balancing mode it stays activated. We then load the data in the sampler to access its size, which incurs some overhead.
The size of a data sample can vary by up to an order of magnitude, which currently leads to skewed usage of both GPU memory and compute. In the worst case a GPU can draw an unlucky batch and run out of memory even 100k steps after training started. …

Load balancing

---

TRAIN.md
scripts/make_lmdb_sizes.py

Provides the script necessary to generate the `metadata.npz` needed for GPU load balancing (#267). 
S2EF sample - 
```
python make_lmdb_sizes.py --data-path path/to/s2ef/all/directory/--num-workers 8
```
IS2RE sample - 
```
python make_lmdb_sizes.py --data-path path/to/is2re/all/data.lmdb--num-workers 8
```
Compatible with both IS2RE and S2EF datasets. While IS2RE metadata files will be uploaded in a future PR, support is provided for both for people interested in using this for alternative datasets.

Load balancing metadata script

---

ocpmodels/common/relaxation/optimizers/lbfgs_torch.py
ocpmodels/common/utils.py
ocpmodels/models/cgcnn.py
ocpmodels/models/dimenet.py
ocpmodels/models/dimenet_plus_plus.py
ocpmodels/models/forcenet.py
ocpmodels/models/schnet.py
ocpmodels/models/spinconv.py

`radius_graph_pbc` only considered the next unit cells for detecting neighbors. This PR lifts this limitation, making the function work for arbitrarily large cutoffs. To do so, we now calculate the number of required unit cells by looking at the closest distance between two cells.
- Remove the `device` argument and obtain it from the passed data.
- Refactored parts of `radius_graph_pbc` for elegance and efficiency
- Split out `get_max_neighbors_mask`, useful for handling neighbors

Fix radius_graph_pbc's 1 unit cell assumption

---

ocpmodels/modules/loss.py
ocpmodels/trainers/base_trainer.py

We previously first calculated the loss average per DDP replica and then averaged across replicas. This leads to wrong results since not every replica has the same number of atoms or even systems. This PR changes the computation to instead calculate an average over all replicas by aggregating the number of samples.
This seems to give a tiny improvement in MAE (0.5% or so). But training looks very similar to previously.

Correctly calculate distributed loss average

---

ocpmodels/common/relaxation/ase_utils.py

Not explicitly mapping to `cpu` causes issues when loading checkpoints with GPU tensors. This ASE calculator isn't meant to be compatible with GPUs so CPU hardcoding is fine.

explicit cpu map

---

ocpmodels/models/spinconv.py

Running spinconv outside the trainers runs into `Floating point exception (core dumped)` errors during the model forward pass. This PR resolves that issue by explicitly defining the device to be used in the output block.

missing spinconv device definition

---

ocpmodels/models/gemnet/gemnet.py
ocpmodels/trainers/base_trainer.py

Gradient scaling for shared parameters didn't work previous since it used `trainer.model` instead of `trainer.model.module`. Also, GemNet-T passed modules instead of parameters. This fixes these two issues.
Additionally, we now also show a warning if a shared parameter has no gradient, which usually means that it doesn't point to a PyTorch parameter.

Fix shared parameter gradient scaling

---

ocpmodels/trainers/base_trainer.py

Resolves bug when trying to use `best_checkpoint.pt` to make predictions. Since `ema`  is present in the config but `checkpoint["ema"]` is not, the model ends up loading random EMA weights.

bugfix loading best_checkpoint.pt

---

ocpmodels/trainers/energy_trainer.py
ocpmodels/trainers/forces_trainer.py

Resolves #290 This PR removes obsolete lines for checkpointing. The following lines already cover the case where no validation is defined:
`forces_trainer`: https://github.com/Open-Catalyst-Project/ocp/blob/f34a0af36671442754c833c21b857f4c307437b7/ocpmodels/trainers/forces_trainer.py#L459-L465
`energy_trainer`: https://github.com/Open-Catalyst-Project/ocp/blob/f34a0af36671442754c833c21b857f4c307437b7/ocpmodels/trainers/energy_trainer.py#L315-L317
In both trainers `eval_every` will control how often a checkpoint gets saved out.

bugfix: checkpoint with no val set Ref. #290

---

README.md
scripts/download_data.py

Resolves #293 
Adds a `--data-path` argument to the `download_data.py` script to allow users to download/uncompress/process a downloaded dataset into a different directory rather than the local directory - `ocp/data`.
Default configs expect the dataset to live in `ocp/data`, make sure to symlink your directories or modify the `base.yml` configs accordingly to specify the correct paths.

add data-path arg to download script

---

ocpmodels/common/relaxation/optimizers/lbfgs_torch.py
ocpmodels/common/utils.py
ocpmodels/trainers/forces_trainer.py

* We call `torch.cuda.empty_cache()` after each relaxation step which is causing a big slowdown in relaxations. Calling it only at the end of the relaxation gives a >5x speedup for 216 Gemnet-Q model, and >4x for the 39M model: [benchmarks](https://docs.google.com/spreadsheets/d/1iws5eT0ZdyyWsJALOdu11JyJbhP2plJkTuWO4cvZR1c/edit?usp=sharing)
* Support for resuming relaxations: If all the traj files for a batch already exist, we skip running the relaxation. Note that this does not compute the metrics correctly (This can be fixed in a later PR by reading the relaxed state from the traj files).
* Changed the traj file writing from `append` mode to `write` mode. Our data loader contains a few repeated examples, which causes multiple relaxation trajectories to be written to the same traj files. …

Speedup relaxations and support for resuming relaxations

---

ocpmodels/common/utils.py
ocpmodels/models/gemnet/gemnet.py

GemNet currently hardcodes PBC graph calculation with no flag to offer an alternative like other models in the repo i.e.
https://github.com/Open-Catalyst-Project/ocp/blob/ae6cf263abd9a027291cc8c880d41932b4049517/ocpmodels/models/spinconv.py#L205-L228
Replicating MD17, COLL, QM9, and other no-pbc datasets is not possible unless the dataset is constructed with an extremely large unit cell. This PR adds the `use_pbc` flag to allow users to use `raidus_graph` instead of our `radius_graph_pbc` implementation.

no-pbc gemnet support

---

.gitattributes

Minor - per recent tutorial changes, repo stats report as majority jupyter notebooks which is misleading due to how things are saved there. This removes ipynb notebooks from those stats.

remove ipynb from language stats

---

env.common.yml
ocpmodels/common/utils.py

Recent updates to `setuptools` breaks demjson - https://github.com/dmeranda/demjson/issues/40. Since demjson isn't used in the repo we can just remove it rather than downgrading setuptools.
Resolves #320

demjson env fix

---

ocpmodels/common/utils.py
ocpmodels/datasets/single_point_lmdb.py
ocpmodels/datasets/trajectory_lmdb.py

PyG >= 2.0 has an updated data format which causes our script to crash when running with PyG >= 2.0, due to the fact that our LMDBs store each data point as the bytes of the pickled PyG data object. 
This PR adds a simple function that converts the old (pickled) PyG < 2.0 `Data` objects to the new PyG >= 2.0 `Data` format if the current PyG version is >= 2.0.

Added support for PyTorch Geometric 2.0's updated Data format

---

ocpmodels/datasets/lmdb_dataset.py

The PyG-2 update transform is somewhat broken after #310. This update transform should run before any other code that accesses the PyG data objects (otherwise we will get an error). I've fixed that order in this PR.

PyG 2 Support Regression

---

ocpmodels/common/utils.py

This will allow us to get the inner function using the `model.forward.__wrapped__` attribute.
Use-case:
If we want to inspect the accepted parameters of the forward method of some model (that uses `conditional_grad`), we will not be able to cleanly do so (using the `inspect` module) as the forward method is wrapped using our function. With this PR, we can just use `inspect.signature(model.forward.__wrapped__)`.

Update `conditional_grad` decorator to use `functools.wraps` on the original function

---

ocpmodels/trainers/energy_trainer.py
ocpmodels/trainers/forces_trainer.py

When defining datasets in the yaml configs via a dictionary format e.g.
```
dataset:
train:
src: data/s2ef/200k/train
normalize_labels: False
val:
src: data/s2ef/all/val_id_30k
```
The current codebase registers all possible datasets in the config - https://github.com/Open-Catalyst-Project/ocp/blob/fe9998ecbe47e7984a5fa833fd9e4684e58b005b/ocpmodels/trainers/base_trainer.py#L162-L165 This results in the following error `AttributeError: 'ForcesTrainer' object has no attribute 'test_dataset'` once reaching these lines: https://github.com/Open-Catalyst-Project/ocp/blob/fe9998ecbe47e7984a5fa833fd9e4684e58b005b/ocpmodels/trainers/forces_trainer.py#L407-L410 since the condition is only examining if the key exists in `self.config` rather than checking if a valid entry exists.
This issue is …

bugfix for dict dataset definition

---

ocpmodels/models/gemnet/fit_scaling.py

An earlier PR removed `is_vis`, this script breaks otherwise.

gemnet scaling script fix

---

.pre-commit-config.yaml
ocpmodels/common/distutils.py

This PR makes two changes:
1. Removes extra context on GPU0 during distributed training by setting the default device to local_rank  i.e. `torch.cuda.set_device(local_rank)`. My understanding is that certain operations like dataloading with memory pinning can create extra context on rank 0. I have seen two situations where this ends up being significant, one is training with apex optimizers (I am guessing this is model agnostic), the other is training NequIP. Below I have attached an example.
Without setting `torch.cuda.set_device(local_rank)`
Setting `torch.cuda.set_device(local_rank)`
2. Unrelated to the first change but we need to pin the version of click for black with pre-commit or update the rev https://github.com/psf/black/issues/2964#issuecomment-1080974737

Removes extra context on GPU0 for distributed training

---

configs/is2re/example.yml
configs/s2ef/example.yml
ocpmodels/modules/loss.py
ocpmodels/trainers/base_trainer.py
ocpmodels/trainers/forces_trainer.py

Scales L2 loss for forces by the no. of atoms in the structure.
Better default than picking an arbitrary constant force coefficient across structures of different sizes, and should allow for a 1:1 relative weighting of energy to force loss to work reasonably well.
Can be used by setting `loss_force: atomwisel2` in the config (make sure to set `force_coefficient: 1`).

Atomwise L2 loss

---

ocpmodels/trainers/forces_trainer.py

There was a bug in the logic for deciding whether to checkpoint based on val error metrics, causing it to always save the most recent weights. This PR fixes that.

Bugfix in best val metric check for checkpointing

---

ocpmodels/modules/loss.py
ocpmodels/trainers/base_trainer.py

https://github.com/Open-Catalyst-Project/ocp/blob/d3fc9d08173c968c92bae330a8d4b850822c2d24/ocpmodels/trainers/forces_trainer.py#L519 `batch_size` is only a valid argument when using `DDPLoss`. This PR resolves that for instances with only 1 GPU. Alternatively, we can remove this condition https://github.com/Open-Catalyst-Project/ocp/blob/d3fc9d08173c968c92bae330a8d4b850822c2d24/ocpmodels/trainers/base_trainer.py#L451 and have all losses go through `DDPLoss` regardless of GPUs since `all_reduce` is still a valid call under 1 GPU. I've tested both approaches and they work fine. Any preference?

atomwise l2 bugfix for non-ddp 

---

ocpmodels/trainers/forces_trainer.py

Small fix to PR #343 - it assumes all configs have `loss_force` in their configs. Defaults `loss_force` to what we define [here](https://github.com/Open-Catalyst-Project/ocp/blob/922ec72e1e20637fb5b537f304d797779bd46a4d/ocpmodels/trainers/base_trainer.py#L439)

bugfix PR#343

---

.circleci/config.yml
.pre-commit-config.yaml
env.common.yml
env.cpu.yml
env.gpu.yml
ocpmodels/common/relaxation/optimizers/lbfgs_torch.py
ocpmodels/common/utils.py
ocpmodels/models/gemnet/layers/basis_utils.py
ocpmodels/models/gemnet/layers/radial_basis.py
ocpmodels/models/gemnet/utils.py
ocpmodels/models/painn/painn.py
ocpmodels/models/painn/utils.py
ocpmodels/models/spinconv.py

Current installation instructions are outdated and cause issues (see CI builds and #348). This updates wheels. Note #336 will replace this as a conda-only installation is a lot cleaner, but we'll need to wait until PyG 2.0.5 hits conda as it currently has a bug with DimeNet++.

Update environment installation

---

DATASET.md

Includes a download to OC20 Bader charge data analysis ran as part of the original paper release. Bader charge analysis is provided for all final frames of our train+validation systems (for both S2EF + IS2RE/RS).
For more details on the analysis - visit https://theory.cm.utexas.edu/henkelman/research/bader/

OC20 Bader charge data release

---

DATASET.md

Remove an unexpected character `%7C` in the OC22-S2EF download address

Correct OC22 download address

---

ocpmodels/common/utils.py

Resolves #366.
Data created in PyG>2 ends up getting converted again [here](https://github.com/Open-Catalyst-Project/ocp/blob/bfd2d62758896ee38132636c03fdce43df2e2fe7/ocpmodels/common/utils.py#L35-L42) resulting in an empty Data object. This PR only runs this method if PyG>2 wasn't used for data construction. The same logic is used directly from PyG to check if new vs. old data is being used - https://github.com/pyg-team/pytorch_geometric/blob/a8601aafd7fc52b87b3f85e86013e64cb7af3e2d/torch_geometric/data/data.py#L422-L427.
Thanks @AdeeshKolluru!

Bugfix: Data created with PyG>2.0

---

ocpmodels/trainers/base_trainer.py

For slurm job arrays, log files are created as `"$SLURM_ARRAY_JOB_ID"_"$SLURM_ARRAY_TASK_ID".*`, instead of `"$SLURM_JOB_ID".*` ([source](https://slurm.schedmd.com/job_array.html)).

Log correct job id for slurm arrays

---

.circleci/config.yml

It seems like having separate `run` commands when the cache is not stored errors out as seen [here](https://app.circleci.com/pipelines/github/Open-Catalyst-Project/ocp?branch=painn_nan_fix).

Circle CI - merge conda install and create env runs

---

ocpmodels/models/gemnet/layers/scaling.py
ocpmodels/models/gemnet_gp/layers/scaling.py
ocpmodels/models/gemnet_oc/gemnet_oc.py
ocpmodels/models/painn/painn.py

These changes simply allow checkpoints to be loaded that have the path to a scale_file replaced with the full scale file dictionary. It doesn't include any functionality for actually modifying the checkpoints to store scale files that way.
It is also still compatible with loading scale files from their path, it just checks to see if it is a path or a dictionary.

Load attached scale file

---

ocpmodels/models/base.py
ocpmodels/models/gemnet_oc/gemnet_oc.py

Bug from #378 affecting all GemNet-OC training / inference runs.
[`otf_graph` is set](https://github.com/Open-Catalyst-Project/ocp/blob/main/ocpmodels/models/gemnet_oc/gemnet_oc.py#L901) but never used in `generate_graph`. [The function uses `self.otf_graph`](https://github.com/Open-Catalyst-Project/ocp/blob/main/ocpmodels/models/base.py#L33).
Same for other parameters `self.cutoff_aint`, `self.max_neighbors_aint`.

Bugfix: use correct otf_graph, cutoff, max_neighbors for GemNet-OC graphs

---

ocpmodels/models/gemnet_oc/gemnet_oc.py
ocpmodels/models/painn/painn.py
ocpmodels/trainers/base_trainer.py

PR to load checkpoints with scaling factors packaged within them. @brookwander is helping test this.
I've updated all released GemNet-OC and PaiNN checkpoint files to include scaling factors and not require a separate scale file.

Load scaling factors from checkpoint if available

---

ocpmodels/models/base.py
ocpmodels/models/cgcnn.py
ocpmodels/models/dimenet.py
ocpmodels/models/dimenet_plus_plus.py
ocpmodels/models/forcenet.py
ocpmodels/models/gemnet/gemnet.py
ocpmodels/models/gemnet_gp/gemnet.py
ocpmodels/models/gemnet_oc/gemnet_oc.py
ocpmodels/models/painn/painn.py
ocpmodels/models/schnet.py
ocpmodels/models/scn/scn.py
ocpmodels/models/spinconv.py

Bug from #378. DimeNet and DimeNet++ were [using offset indices instead of offset distances](https://github.com/Open-Catalyst-Project/ocp/blob/bbd02315601aaf12cd90a546eae6fcd2b15ef308/ocpmodels/models/dimenet_plus_plus.py#L413-L414).

Bugfix: use correct offset distances in DimeNet, DimeNet++

---

ocpmodels/common/utils.py

The most recent addition of the `new_training_context` function introduced a rare crash that happens when training resumes from a pre-emption event (see stacktrace below). 
```
2022-09-17 16:30:23 (ERROR): Submitted job triggered an exception
Traceback (most recent call last):
File "/private/home/abhshkdz/.conda/envs/ocp-dev-jun2/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/private/home/abhshkdz/.conda/envs/ocp-dev-jun2/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/private/home/abhshkdz/.conda/envs/ocp-dev-jun2/lib/python3.9/site-packages/submitit/core/_submit.py", line 11, in <module>
submitit_main()
File "/private/home/abhshkdz/.conda/envs/ocp-dev-jun2/lib/python3.9/site-packages/submitit/core/ …
```

Fix pre-empt recovery crash

---

.circleci/config.yml

per - https://circleci.com/docs/using-macos#available-resource-classes, `large` resource class for mac is unsupported without a plan. Reduce to `medium` to get accompanying CI build to run.

reduce macos resource class

---

ocpmodels/common/relaxation/ase_utils.py
ocpmodels/trainers/base_trainer.py

OCPCalculator relied on the "dataset" type to classify energy/force trainer. This introduces bugs for the newer datasets (OC22) that started using the newer class - LmdbDataset.
Open to other options, but this does the trick that's also backwards compatible.

alt trainer identifier

---

ocpmodels/common/relaxation/ase_utils.py

Resolves the bug in `OCPCalculator` when `config_yml` and `checkpoint` are both fed - throws an error when trying to access `model_attributes`. Originally raised  https://discuss.opencatalystproject.org/t/ocpcalculator-ase/221/4
Edit - Some checkpoints that have `relax_dataset` specified, will also throw an error as the trainer will try to load that dataset. Remove that from the config as it's unneeded for the calculator.

OCPCalc edge cases

---

ocpmodels/models/dimenet_plus_plus.py

pyg 2.1 uses a helper function to load activation functions. This small change is motivated by the pyg dimenet++ implementation.

Update dimenet_plus_plus to use pyg activation function resolver

---

ocpmodels/common/relaxation/ase_utils.py
ocpmodels/common/utils.py
ocpmodels/preprocessing/atoms_to_graphs.py

This PR is intended to address Issue #428 which relates to the handling of PBC in OCPCalculator. Previously, #394 allowed radius_graph_pbc to support all possible PBC configurations, but this option was not accessible to users.
Summary of changes:
- AtomsToGraphs can optionally return the PBC configuration of the ASE atoms object (off by default)
- OCPCalculator enables this option
- radius_graph_pbc will check if the PBC configuration is included in the data object. If yes, it will use that configuration. Otherwise, it will now default to [True, True, True].
Because AtomsToGraphs is widely used (constructing LMDBs, etc.), this implementation should enable some flexible PBC options for both training and inference. 
Different PBC configurations for different structures in the same batch is …

Use PBC configuration from ASE atoms objects

---

ocpmodels/trainers/forces_trainer.py

Our most recent models (SCN, GemNet*) use [L2MAE](https://github.com/Open-Catalyst-Project/ocp/blob/main/ocpmodels/modules/loss.py#L7) as the default force loss. This PR adds support for using tag weights with L2MAE.

Support for using tag weights with L2MAE force loss

---

ocpmodels/models/gemnet_oc/gemnet_oc.py
ocpmodels/trainers/base_trainer.py

This is a preliminary PR to add an interpolation for atomic number embeddings. For example, if a trained or pre-trained checkpoint has never seen a specific element before, the embeddings for that element are essentially random and unhelpful, but we would expect them to be correlated to embeddings of nearby elements. 
This implementation uses a simple RBF-based interpolation strategy from scipy, with the atomic row and group as input features. 
Every model will have separate atomic embeddings that might need to be updated, so an example of the necessary information has been added to the gemnet_oc model. Similar changes would be needed for every other model that might benefit from this interpolation.

Periodic table embedding strategy for unseen elements

---

.circleci/config.yml
INSTALL.md
env.common.yml
env.cpu.yml
env.gpu.yml
ocpmodels/models/schnet.py

- Upgrades to pytorch 1.13.1, cuda 11.6, pyg 2.2.0.
- ~Moves conda-forge packages to pip install.~ 
- Conda-only install using mamba (supersedes #336).
- Removes windows test (has turned out to be finicky to support).

Upgrades to pytorch 1.13, cuda 11.6, pyg 2.2.0

---

configs/s2ef/example.yml
ocpmodels/common/relaxation/ml_relaxation.py
ocpmodels/common/relaxation/optimizers/lbfgs_torch.py
ocpmodels/trainers/forces_trainer.py

Makes the following changes to the way we save relaxations:
- ASE/VASP convention refers to the 0th step as being the initial atoms object, updates the logic to save out the initial frame and then run N-1 steps.
- Adds a flag to control what data gets saved during relaxations:
- `save_full_traj=1` (default) saves every frame
-  `save_full_traj=0` saves only the initial and final frame
- Cleans up the relaxation code pursuant to #440 
Storage usage on Val-ID (~25k systems):
`save_full_traj=1`: 32G
`save_full_traj=0`: 288MB
As a sanity check I ran OC20 Val-ID relaxations to compare performance:
Old: 0.3398710582458926 eV
New (`save_full_traj=1`): 0.33946821912398933 eV
New (`save_full_traj=0`): 0.3389780476024761 eV
Edit: Per the latest changes-  
Old: 0.3398710582458926 eV
New …

Relaxation storage optimizations

---

configs/s2ef/example.yml
ocpmodels/datasets/lmdb_dataset.py

When running inference, multiple 1 GPU jobs can often be faster than a multi-gpu/node job due to potential overhead and communication involved. 
This PR supports the availability to shard a defined dataset into appropriate chunks. A process launched with the following config will partition the dataset in 5 approximately equal chunks and only run on the 0th shard. 
```
relax_dataset:
src: path/to/data
shard: 0
total_shards: 5
```
To run inference on the full dataset under this use case, 5 jobs must be launched with `shard` set from 0-4.
Benchmark:
GemNet-OC on 10k systems, averaged across 5 runs each.
GPUs | GPU-sec/RX
-- | --
1 | 6.84
8 | 9.65
64 | 11.23

Support dataset sharding

---

ocpmodels/common/relaxation/ml_relaxation.py

Looks like when https://github.com/Open-Catalyst-Project/ocp/pull/447 was merged it removed the definition of `save_full_traj`.

Improper OOM merge fix

---

ocpmodels/models/escn/escn.py
ocpmodels/models/scn/sampling.py

Resolves #461 
One of the efficiency improvements eSCN made is that it computes spherical harmonic weights [once in the initialization](https://github.com/Open-Catalyst-Project/ocp/blob/ad06ac85b943edcb596905241487ca8e63e34c2b/ocpmodels/models/escn/escn.py#L206-L220.) that gets used throughout training. This is contrary to how SCN originally did it, where it computed them at [each forward pass](https://github.com/Open-Catalyst-Project/ocp/blob/ad06ac85b943edcb596905241487ca8e63e34c2b/ocpmodels/models/scn/scn.py#L390-L395).
The way it's currently setup, however, is it hardcodes a device in the model `__init__`  https://github.com/Open-Catalyst-Project/ocp/blob/ad06ac85b943edcb596905241487ca8e63e34c2b/ocpmodels/models/escn/escn.py#L121 which conflicts with the true device the repo is …

eSCN CPU support

---

ocpmodels/datasets/lmdb_dataset.py
ocpmodels/datasets/oc22_lmdb_dataset.py

Generalize the code for loading folders of LMDB folders so that it works for
* Any keys are fine for the LMDB (not just 0->len(lmdb)), just like for LMDB file logic
* Ignore the "length" key which was included in older LMDB files and rely instead on the number of keys that are not "length"
Together, these changes also mean that any file that works as an LMDB in a folder of LMDBs will also work as a specific LMDB for training!

LMDB folder fix

---

ocpmodels/datasets/lmdb_dataset.py
ocpmodels/datasets/oc22_lmdb_dataset.py

* first stab at lmdb len fix
* slight refactor so that the encode works correctly
* add readahead as default for lmdb, add some more docs to the lmdb dataset class
* same changes for oc22 dataset objects as for the default LmdbDataset

LMDB folder fix (#476)

---

ocpmodels/common/utils.py
ocpmodels/models/base.py
ocpmodels/models/gemnet_oc/gemnet_oc.py

This PR adds a new option to [`get_mask_neighbors_mask`](https://github.com/Open-Catalyst-Project/ocp/blob/a8ac36d75fc60d5b6d54b4019502941eb868fed0/ocpmodels/common/utils.py#L721) that enables more consistent handling of edges with the same length. Previously, this function would strictly enforce the maximum number of edges. This required a "tie-breaking" procedure in highly ordered bulks with many degenerate edges. It turns out that the tie-breaking was 1. biased based on unit cell construction and 2. inconsistent for identical structures with different unit cells. This problem is evident in Issue #428.
The default behavior is to continue enforcing the max strictly. However, this constraint can now be disabled with the option `enforce_max_strictly = False`. With this setting, …

Allow models to include degenerate edges

---

env.common.yml
ocpmodels/datasets/ase_datasets.py
ocpmodels/datasets/lmdb_database.py
ocpmodels/datasets/lmdb_dataset.py
ocpmodels/datasets/oc22_lmdb_dataset.py
ocpmodels/datasets/target_metadata_guesser.py
ocpmodels/preprocessing/atoms_to_graphs.py
tests/datasets/test_ase_datasets.py
tests/datasets/test_ase_lmdb.py

PR to add a custom LMDB-based ASE database and support for multiple/arbitrary targets.
To enable more flexible and multi-property models, datasets can now be asked for their target metadata. Ideally this would come from the user who made the original datasets (and include things like units/etc), but the metadata can also be guessed from the data itself. 
You can get the metadata from `dataset.get_metadata()`, which will either return the metadata in the DB/etc, or guess it by looking at the shapes if that's not present.
The trainer is free to use or discard this metadata as needed, but the hope is that this enables flexible trainers that adapt to whatever dataset is plugged in!
Example metadata:
```
db.metadata = {
"targets": {
"energy": {
"extensive": False,  # extensive = sum pooling …
```

LMDB-based ASE dataset, generic targets, target metadata guessing

---

ocpmodels/models/equiformer_v2/trainers/forces_trainer.py

The scheduler setup for EquiformerV2 uses the training dataloader to convert epochs to steps, which doesn't work when initializing the model with `OCPCalculator` since there's typically no training dataset. This PR avoids setting up the scheduler for EquiformerV2 when there isn't a training set and the following should work now (refs #540):
```python3
from ocpmodels.common.relaxation.ase_utils import OCPCalculator
calc = OCPCalculator(checkpoint='eq2_83M_2M.pt', cpu=False)
```

Skipping scheduler setup in EquiformerV2 trainer if train_loader isn't defined

---

cli.py
env.common.yml

Add click for cli generation with placeholders for supported methods. Examples:
```
$ python cli.py --help
Usage: cli.py [OPTIONS] COMMAND [ARGS]...
Graph networks for electrocatalyst design
Options:
--help  Show this message and exit.
Commands:
download
finetune
predict
relax
train
validate
```
```
$ python cli.py download --help
Usage: cli.py download [OPTIONS]
Options:
Logging: 
--log-level [ERROR|WARNING|WARN|INFO|DEBUG]
The minimum level of log statements to print.  [default: INFO]
--help                          Show this message and exit.
```
\* We'll add a setup file later that will let us replace `python cli.py` with `ocp`

[cli] Add cli skeleton

---

cli/cli.py
cli/runner.py
ocpmodels/common/utils.py

Adds a `train` method to the cli. Updates the [method that creates the `config` dictionary](https://github.com/Open-Catalyst-Project/ocp/pull/575/files#diff-d49941eeb80aee5a28d712edbb457ef26de109848fd6729361a47174e4c38ccbR423) to use these explicitly-provided values rather than an argparse namespace. Training itself is unchanged - only the methods to parameterize the training run are updated.
Most command line arguments are the same. One exception is the method used to override specific values in config.yml. In the past, overriding would have used the specific field as the cli option, e.g. `--optim.batch_size=10`. Now we use a `--config` option, e.g. `--config optim.batch_size=10`; this `--config` option can be used more than once to set multiple values.
```
$ python -m cli.cli train …
```

Cli train impl

---

.circleci/config.yml
ocpmodels/datasets/oc22_lmdb_dataset.py
ocpmodels/models/equiformer_v2/equiformer_v2_oc20.py

This is primarily to support the latest EquiformerV2 models we've been training on OC22 (#577), that use per-element linear references.
During training and validation, these references are subtracted off the energy targets as usual in the OC22 dataloader. But during testing and prediction, these references need to be added to the model's energy prediction. The latter is currently unsupported in the codebase.
There are a few different options of how to go about this:
1. We could re-use the coefficients from the dataloader by adding additional logic to the `predict` function in the trainer, but that makes invoking these models through the ASE calculator tricky since in that workflow there typically isn't a dataloader.
2. There's a similar issue if we add a path to the coefficients numpy …

Adds optional per-element linear reference coefficients to EquiformerV2

---

DATASET.md
MODELS.md

Released DDEC charges per external request (https://github.com/Open-Catalyst-Project/ocp/issues/601) and added a note clarifying reg relaxations for IS2RS and IS2RE (https://github.com/Open-Catalyst-Project/ocp/issues/600).

DDEC release and IS2RS clarification for ODAC23

---

.circleci/config.yml

Previous version started to fail CI, https://app.circleci.com/pipelines/github/Open-Catalyst-Project/ocp/2032/workflows/b691e1ab-2cd5-43b8-b017-f2c2ccff91ef/jobs/4097 , unclear why but bumping miniconda version fixes this

bump miniconda version

---

ocpmodels/trainers/ocp_trainer.py

The scale factor from `self.scaler.get_scale()` potentially gets modified in `self._backward()`. It's a problem to use the updated value because then the loss is calculated incorrectly in L171 (it's often off by a factor of 2 during early training).

Fix amp scale factor for loss

---

tests/models/test_equiformer_v2.py
tests/models/test_escn.py

Inside the two different SO3 embedding classes for eSCN / Equiformer there are two permutation transformations that permute coefficients to be L or M primary (_l_primary, _m_primary). This adds two tests to make sure these permutation matrices work as expected. 
L primary format coefficients should appear in the order
L0M0, L1M-1, L1M0, L1M1, L2M-2, ...
M primary format coefficients should appear in the order
M0L0, M0L1,..., M0Lmax, followed by
M1L1, M1L2, ..., M1Lmax, followed by
M(-1)L1, M(-1)L2, ... , M(-1)Lmax ...
A coefficient test matrix where the value of the coefficients has a 1 to 1 mapping with its LM values. 
The mapping is as follows
1.01 -> L=1, M=1
1.02 -> L=1, M=2
-1.01 -> L=1, M=-1
0.0 -> L=0, M=0
-3.04 -> L=3, M=-4
After permuting the matrix the coefficients are verified …

Add in tests for coefficient mapping, mprimary, lprimary

---

ocpmodels/common/utils.py
ocpmodels/trainers/ocp_trainer.py

Fixes to adapt from batch_list to batch in run_relaxations module.

Minor fix in run_relaxations

---

ocpmodels/datasets/ase_datasets.py

I think the linear reference should be computed in the models as part of #556 or in the trainer, but for now we can match the `oc22_dataset`, and deprecate this later.

lin ref in ase datasets

---

ocpmodels/trainers/ocp_trainer.py

Currently the function _compute_metrics() takes as input a dictionary (out) that contains tensors as values. These values are modified inside of _compute_metrics() , which means the callers version of these tensors are also modified. 
```
out=forward(batch)
_compute_metrics(out)
out # no longer the same values as from forward(batch)
```

change _compute_metrics not to modify callers version

---

ocpmodels/common/utils.py

This replaces the .ignore file logic that automatically includes modules from all experimental user directories *except* for a select few with a .include file that only includes user directories which are requested. For now, there is also some additional logic that if the .include does not exist and there is a directory that is the same as the current user's name, that will be included.

Invert experimental import logic to opt-in

---

ocpmodels/common/utils.py
tests/common/test_yaml_loader.py

If you specify the same key in a config the current default behavior is to overwrite the value of the key with latest entry. For example something like, 
```
key1: 
- a 
key1:
- b
```
Would result a dictionary 
```
d={'key1':'b'}
```
This commit throws an error when such a situation occurs. This can prevent a user from accidentally specifying a value twice in a config that is not actually being used (overwritten by last entry).

add unique key loader check to YAML to avoid problematic configs

---

.github/workflows/test.yml
tests/conftest.py
tests/demo/ocpapi/tests/integration/client/test_client.py

Added an option to pytest, 
--skip-ocpapi-integration
When it is present then ocpapi integration tests that hit the rate limiting API are skipped
if pytest is run without this flag , all tests available are run

skip ocpapi integration tests in default test workflow

---

docs/tutorials/cattsunami_walkthrough.md
src/fairchem/applications/cattsunami/README.md

The summary fig was linked to the old repo and the dissociation scheme image never got copied over. This PR fixes these two things.

fixing summary fig and dissociation scheme fig in the gitbook

---

docs/tutorials/cattsunami_walkthrough.md
src/fairchem/applications/cattsunami/tutorial/workbook.ipynb

adding random seed so there exists a frame set at the completion on adsorbate enumeration. This is because there are so few sites to accommodate running on CPU that sometimes there are no frame sets at the end of enumeration. In actual use, many more configs should be used.

adding seed to md tutorial and ipynb

---

src/fairchem/core/common/data_parallel.py
src/fairchem/core/trainers/base_trainer.py
tests/core/common/test_data_parallel_batch_sampler.py

Currently we do not pass the seed through to our BalancedBatchSampler and a seed=0 is used by default. This changes that so the seed specified on command line is passed through to permute the order of our data.

pass seed to sampler

---

src/fairchem/core/scripts/preprocess_ef.py

Resolves https://discuss.opencatalystproject.org/t/error-in-converting-to-lmdb-format-for-s2ef-dataset/474.
Our preprocessing code no longer saves energy as `y`: https://github.com/FAIR-Chem/fairchem/blob/1b4b62b4b71dfe755c94c60839f5d810e5d14a91/src/fairchem/core/preprocessing/atoms_to_graphs.py#L197-L199

update preprocess script

---

src/fairchem/core/_cli.py
src/fairchem/core/common/distutils.py
tests/core/test_cli.py

Add option to launch distributed runs locally with >1 GPU. Useful for testing parallel algorithms locally. This uses torch elastic API which just spawns python multiprocesses under the hood.
This is equivalent to calling our application with [torchrun](https://pytorch.org/docs/stable/elastic/run.html ) ie: `torchrun fairchem ...`, but makes the interface cleaner so we dont need to work with 2 launchers
Note: torchrun just calls the [elastic launch API](https://github.com/pytorch/pytorch/blob/main/torch/distributed/launcher/api.py#L30) under the hood
There's a bug where LMBDs cannot be pickled (needed for multiprocessing), this is resolvable by setting num_workers to 0 which is ok for local mode testing.
examples:
To run locally on 2 GPUs with distributed:
```fairchem --debug --mode train …
```

Add option to launch distributed runs locally with >1 GPU

---

src/fairchem/core/common/relaxation/ase_utils.py
src/fairchem/core/common/utils.py
src/fairchem/core/trainers/base_trainer.py

Handle updating checkpoints with new format configs that were saved with 'loss_fns' and 'eval_metrics' according to #724

Config fix

---

packages/fairchem-core/pyproject.toml

Ruff was unpinned and upgraded to 0.5, which started triggering lint issues

pin ruff to 0.4.10

---

docs/core/inference.md
src/fairchem/core/trainers/base_trainer.py

- In my own private fork of the repo I noticed this issue where I had to specify the train dataset to get the models to predict.
- This was the change I made to work around this.
- I do not have your training dataset so I haven't verified that it doesn't break your models. But I saw the comment in the readme and thought I'd let you know the issue!

No longer need to specify train dataset loader when predicting

---

packages/fairchem-core/pyproject.toml

importlib is breaking multiprocess pickling.
pytest locally works for tests that uses python multiprocess: 
eg: `pytest tests/core/common/test_gp_utils.py` (from eq2_graph_parallel branch)
but on CI, which uses `./packages/fairchem-core/pyproject.toml` was breaking with errors like:
```
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/private/home/rgao/micromamba/envs/fair-chem/lib/python3.11/multiprocessing/spawn.py", line 122, in spawn_main
exitcode = _main(fd, parent_sentinel)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/private/home/rgao/micromamba/envs/fair-chem/lib/python3.11/multiprocessing/spawn.py", line 132, in _main
self = reduction.pickle.load(from_parent)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'private'
```
I traced this …

Try removing importlib - breaks multiprocess pickling

---

src/fairchem/core/common/logger.py
src/fairchem/core/trainers/base_trainer.py

[wanbd.watch](https://docs.wandb.ai/ref/python/watch) logs too much data and makes the UI slow, turn it off by default.
Example usage (config in yaml):
```
logger:
name: wandb
entity: fairchem
project: fm_testing
watch: 1000
```
the number specifies the frequency (in # of steps) to log gradients etc..
Run without watch: https://fairwandb.org/fairchem/fm_testing/runs/2024-07-02-16-12-48-local_test_no_watch
Run with watch: https://fairwandb.org/fairchem/fm_testing/runs/2024-07-02-16-10-40-local_test_watch

Hide wandb.watch behind flag

---

src/fairchem/core/_cli.py
src/fairchem/core/common/flags.py

FAIRCluster uses partitions while AWS uses slurm-account and slurm-qos (https://docs.google.com/document/d/19AJC5sL17t4f2zzn6ylW6-mO0CGeONs8ogKprMrWNxA/edit#heading=h.lbn5dlaajt5m)
For FAIRCluster use: 
slurm-partition: {ocp, learnfair, etc..}
For AWS:
slurm-partition: learn
slurm-account: ocp
slurm-qos: {ocp_high, lowest}

Add slurm qos setting

---

src/fairchem/core/models/equiformer_v2/transformer_block.py

1 line change, this is needed for activation checkpointing to work if we want the interface to remain passing SO3_embedding objects to the transformer. In normal operation the code is not wrong but error prone because the function modifies the input inplace, which the user does not expect. See https://fairwandb.org/fairchem/fm_testing/reports/Training-Instability-of-Large-EQV2-Models--Vmlldzo0MzI5NQ for more details
The alternative solution is to change the transformer.forward signature to take tensors instead but this introduces more breaking changes in the code
* introduces tiny memory diffs: https://fairwandb.org/fairchem/fm_testing/reports/Clone-vs-no-clone-input-to-transformer--Vmlldzo0MzQ5Nw

clone so3 embedding object

---

src/fairchem/core/models/equiformer_v2/equiformer_v2.py
src/fairchem/core/models/escn/escn.py
src/fairchem/core/models/gemnet_oc/gemnet_oc.py
src/fairchem/core/models/painn/painn.py
tests/core/e2e/test_s2ef.py
tests/core/models/test_configs/test_dpp.yml
tests/core/models/test_configs/test_dpp_hydra.yml
tests/core/models/test_configs/test_equiformerv2_hydra.yml
tests/core/models/test_configs/test_escn_hydra.yml
tests/core/models/test_configs/test_gemnet_dt_hydra.yml
tests/core/models/test_configs/test_gemnet_dt_hydra_grad.yml
tests/core/models/test_configs/test_gemnet_oc_hydra.yml
tests/core/models/test_configs/test_gemnet_oc_hydra_grad.yml
tests/core/models/test_configs/test_painn.yml
tests/core/models/test_configs/test_painn_hydra.yml
tests/core/models/test_configs/test_schnet.yml
tests/core/models/test_configs/test_scn.yml

The original hydra commit does not play nice with DDP because there are unused parameters. These parameters are the original heads present in the backbone that are duplicated in the heads. To fix this issue this PR sets them to None in the underlying class when it is used through the Backbone class. 
Additionally tests for DDP versions were not present in the code before this. I have added every network to in tests_e2e to be tested in both DDP and non-DDP modes.
A slight issue with DDP tests is that when using spawn method for distributed we cannot properly pickle and load LMDBs. A workaround for now is when testing with DDP , num_workers=0. 
A future BE task could be to re-initialize LMDB hooks in workers instead of pickling them over.

fix issues with ddp/hydra and add tests

---

src/fairchem/core/common/utils.py

Currently we ask developers to put dev code into `fairchem/src/fairchem/experimental`. These paths are then loaded automatically. The current code resolves any paths, so if `fairchem/src/fairchem/experimental` is a symlink (say to a github repo cloned elsewhere) the crawler will fail as the paths do not look relative to the fairchem root. 
This PR would remove the `.resolve()` calls (replacing with `.absolute()` where appropriate) in the import so that the folder will be crawled without resolving symlinks.

Allow symlink'd experimental folder by using absolute and not resolved paths

---

docs/core/inference.md
src/fairchem/core/scripts/download_large_files.py

To resolve transient download error, we will download from s3 via download_large_files. It's not clear if this will 100% resolve the download issue, but we will be able to catch errors and resolve if they arise.

#806: Move data.db to s3 and download via download_large_files

---

src/fairchem/core/models/equiformer_v2/equiformer_v2.py
tests/core/models/test_equiformer_v2.py

Add activation checkpointing to equiformersv2. This is only added to the EquiformersV2Backbone as we plan to deprecate the original Equiformers_v2
Previously tested here: https://fairwandb.org/fairchem/fm_testing/reports/Training-Instability-of-Large-EQV2-Models--Vmlldzo0MzI5NQ
Test also ensure the grads are the same when using act checkpointing

Activation checkpoint equiformersv2

---

src/fairchem/core/models/equiformer_v2/equiformer_v2.py
tests/core/models/__snapshots__/test_equiformer_v2.ambr

nn.Linear initializes with default random uniform weights. This PR just makes sure we re-initialize those weights when we call model.apply(init_weights)

Explicitly initialize weights even if initialization method is "uniform"

---

src/fairchem/core/common/flags.py

This makes it easier to find people's checkpoints and logs given a W&B run
Currently no idea where these files are :(
Now: 
we should also add a config line that identifies which cluster the job is on

Use abs run_dir paths by default

---

src/fairchem/core/models/equiformer_v2/equiformer_v2.py
src/fairchem/core/models/escn/escn.py
tests/core/e2e/test_s2ef.py

If we dont check max num atoms and run on GPU we get a weird CUDA device side assert failure with a line number that has nothing to do with the actual error. This prevents the issue by catching it early and giving a clear error message

Add check to max num atoms

---

src/fairchem/core/models/equiformer_v2/equiformer_v2.py

Add option to predict mean energy in eqv2 energy head, does not change default behavior

add option to apply mean to energy

---

src/fairchem/core/common/logger.py

Add option to specify run groups in W&B

add run group

---

src/fairchem/core/models/gemnet_oc/gemnet_oc.py

Previously if you used `--amp` with gemnet-oc hydra it would fail because of a mismatch in tensor dtypes in the force head (float32 vs float16) at this [line](https://github.com/FAIR-Chem/fairchem/blob/main/src/fairchem/core/models/gemnet_oc/gemnet_oc.py#L1530). 
In the original implementation of gemnet-oc the x_F embeddings are float16 when amp is used, which then get cast as float32 at this [line](https://github.com/FAIR-Chem/fairchem/blob/main/src/fairchem/core/models/gemnet_oc/gemnet_oc.py#L1273). What was happening in the hydra implementation is that when the heads get initialized they are wrapped in amp=False [here](https://github.com/FAIR-Chem/fairchem/blob/main/src/fairchem/core/models/base.py#L313-L315), so in this line: `x_F = self.out_mlp_F(torch.cat(emb["xs_F"], dim=-1))` …

update to gemnet-oc hydra force head to work with amp

---

src/fairchem/data/oc/core/slab.py
src/fairchem/data/oc/utils/vasp.py
src/fairchem/data/oc/utils/vasp_flags.py

ASE reads the pseudopotenials from `VASP_PP_PATH`. This PR supports the ability to read pseudopotentials from a different environment variable.

add docstring. Add support for different pseudopotential path

---

src/fairchem/data/oc/utils/vasp_flags.py

Our OC20 bulks don't explicitly define that ISPIN=1. This is a problem when using ASE to generate VASP inputs since if you're using an atoms object that has magnetic moments attached, it will modify your INCAR to be ISPIN=2 even if you don't define it in your vasp flags - https://gitlab.com/ase/ase/-/blob/master/ase/calculators/vasp/create_input.py?ref_type=heads#L72-76.
OC20 used bulks that explicitly did not have magnetic moments attached to their atoms objects, so the dataset remains unaffected. But it is problematic for bulks being used from other sources where magnetic moments are not stripped and if looking for a non spin calculation in line with OC20 models.

explicitly define ispin for oc20 bulks

---

src/fairchem/core/common/data_parallel.py
src/fairchem/core/common/relaxation/ase_utils.py
src/fairchem/core/models/equiformer_v2/equiformer_v2_deprecated.py
src/fairchem/core/trainers/base_trainer.py
src/fairchem/core/trainers/ocp_trainer.py

Add inference_only option to trainers, so that datasets, optimizer, and other objects not necessary for inference are not loaded from checkpoints.
This is mostly for the OCPCalculator, and makes resolves a handful of issues that otherwise arise:
- no need to delete datasets anymore since these will not be loaded
- creating the trainer will not look for files that were used for training but are not necessary for inference (such as normalizers which are already part of the checkpoint)
- no need to specify the specific trainer when loading a checkpoint in `OCPCalculator`, the default `OCPTrainer` should work almost all of the time.
And deprecate `OCPCollater` in favor of using a partial to set otf_graph.

Add inference_only option to trainers

---

.github/workflows/lint.yml
ruff.toml
src/fairchem/core/_cli.py
src/fairchem/core/common/distutils.py
src/fairchem/core/common/logger.py
src/fairchem/core/common/profiler_utils.py
src/fairchem/core/common/slurm.py
src/fairchem/core/common/test_utils.py
src/fairchem/core/datasets/lmdb_dataset.py
src/fairchem/core/models/base.py
src/fairchem/core/models/dimenet_plus_plus.py
src/fairchem/core/models/equiformer_v2/equiformer_v2.py
src/fairchem/core/models/escn/escn.py
src/fairchem/core/models/escn/escn_exportable.py
src/fairchem/core/models/escn/so3.py
src/fairchem/core/models/escn/so3_exportable.py
src/fairchem/core/models/schnet.py
src/fairchem/core/modules/scaling/fit.py
src/fairchem/core/preprocessing/atoms_to_graphs.py
src/fairchem/core/tasks/task.py

Add ruff formatter for src folder only (for now)

enable ruff formatter

---

packages/fairchem-demo-ocpapi/pyproject.toml

#861 The OCP API package is pinned to requests v2.32.0, which has been yanked. This updates to the most recent version, v2.32.3.

ocpapi dependencies / requests -> 2.32.3

---

src/fairchem/core/common/relaxation/ase_utils.py
src/fairchem/core/trainers/base_trainer.py

Introduced by: https://github.com/FAIR-Chem/fairchem/pull/850/files
inference_only was evaluating to None and not calling the routine to load the trainer state even resuming from training

fix bug where trainer state not being loaded

---

src/fairchem/core/common/logger.py
src/fairchem/core/trainers/base_trainer.py

The singleton logger will let us log from anywhere in the code. This will also replace the old loggers that can be deprecated. User just need to specify logger.name = wandb_singleton
Example Usage (can be placed anywhere):
`WandBSingletonLogger.get_instance().log({"energy": energy.max()}, commit=False)`
Note the `commit = False` will let wandb know the logging of the current isn't complete and will log the output when the step is updated (ie: in the trainer)

Add singleton logger

---

src/fairchem/core/scripts/convert_hydra_to_release.py
tests/core/e2e/test_e2e_commons.py
tests/core/e2e/test_e2e_finetune_hydra.py
tests/core/models/test_configs/test_finetune_hydra.yml

When fine tuning a hydra model we use 'starting_checkpoint', however when releasing a model its redundant to ship both the starting checkpoint and the fine tuned checkpoint. 
This script pulls the corresponding config from starting checkpoint and creates a release version of the fine tuned checkpoint that can be used without referencing the original starting checkpoint.

Add script to make release from fine tuned hydra

---

src/fairchem/core/models/base.py
tests/core/e2e/test_e2e_finetune_hydra.py

Add an option to hydra to freeze the backbone from parameter updates

add hydra freeze backbone option

---

src/fairchem/core/datasets/base_dataset.py

sort them so metadata is always in the same order when multiple files or directories are used in a dataset object

Sort paths in datasets

---

src/fairchem/core/trainers/base_trainer.py

This is a follow-up to PR #909
The original changes were made directly on the main branch of my fork. To continue working on my fork, it was necessary to move these changes to a dedicated feature branch and resubmitting them through this PR. The code changes remain the same.
Apologies for the mess!
> Running user-generated models with the OCPCalculator currently raises an error:
'OCPTrainer' object has no attribute 'ema' at line 621 in the load_checkpoint function of base_trainer.py.
>
>This issue occurs because self.ema is not declared when load_checkpoint is called. The ema attribute is currently declared in load_extras rather than in the __init__ method of BaseTrainer, leading to this error if load_extras is not called beforehand. As a best practice, class attributes should only be …

add ema to BaseTrainer init

---

src/fairchem/core/datasets/ase_datasets.py
src/fairchem/core/datasets/base_dataset.py
tests/core/common/test_data_parallel_batch_sampler.py
tests/core/datasets/test_create_dataset.py

Extend metadata with additional fields present in the NPZ metadata file. Instead of just taking 'natoms' take everything that is present. 
Allow user to specify a filter on the dataset in the format of 
Take all indices that have absolute value of 'some_quantity' less then or equal to 5
```
subset_to:
- op: abs_le
metadata_key: some_quantity
rhv: 5
```
Take all indices that a value of 'some_quantity' in [x,y,z]
```
subset_to:
- op: in
metadata_key: some_quantity
rhv: [x,y,z]
```

Filter based on additional metadata fields

---

docs/core/datasets/omat24.md

Addresses #961, and updates links based on corrections from #942

fix train dataset links and correct val links and sizes

---

src/fairchem/core/common/tutorial_utils.py
src/fairchem/core/preprocessing/atoms_to_graphs.py
tests/core/preprocessing/test_atoms_to_graphs.py

This PR addresses #962 as well as a related bug in which AtomsRow data was not fully copied during dataset splitting.

Misc ASE db bugfixes

---

packages/fairchem-core/pyproject.toml
src/fairchem/core/_cli.py
src/fairchem/core/_cli_hydra.py
src/fairchem/core/common/flags.py
src/fairchem/core/components/runner.py
tests/core/test_hydra_cli.py
tests/core/test_hydra_cli.yml

1. Removes hydra_cli and cli dependency and splits them into two different clis
The new cli will be called like:
`fairchemv2 --config-yml /path/to/yaml [hydra-like config overides]`
This removes the old arg flags completely and moves them into FairchemJobConfig as a structured config:
Users are free to specify the either in the yaml or in the command line as they choose
in yaml:
``` 
job:
scheduler:
num_ranks_per_node: 4
runner:
logger:
```
in command line:
`fairchemv2 --config-yml /path/to/yaml +job.scheduler.num_ranks_per_node=4`
2. Pass the job config to the runner as a property, the runner still some needs some system level params such as run_dir
ie: runner.fairchem_config

Add structured configs to hydra cli, pass cfg to runners

---

src/fairchem/core/datasets/ase_datasets.py
src/fairchem/core/datasets/lmdb_dataset.py
src/fairchem/core/datasets/oc22_lmdb_dataset.py

Currently we perform key_mapping renames and then perform data_object transforms. However data object transforms have hard coded string values. This means that if we change the task and change the key_mapping the same hard coded data transforms will no longer work, i.e. key omat24_energy might not be present. 
On the flip side, if we perform data transforms before key name remapping, this cleans up the transforms since most datasets have the keys energy and not datasetname_energy. 
This PR changes the order so that we first perform data transforms, and then perform key renaming.

change order of key mapping transform

---

src/fairchem/core/_cli_hydra.py
src/fairchem/core/components/runner.py
tests/core/test_hydra_cli.py
tests/core/test_hydra_cli.yml

This enforces config yamls to have no unused keys. The only allowed **top-level keys** now are {"job", "runner"} and keys that are used in variable replacements.
ie: (dataloader: ...) is allowed as long as the yaml references ${dataloader} somewhere.
**OK Config:**
```
replacement_value: 5
job: ...
runner:
x: ${replacement_value}
```
**NOT OK Config:**
```
random_key: 5
job: ...
runner:
x: 10
```

Strictly enforce no unused keys in yaml

---

src/fairchem/core/datasets/base_dataset.py
tests/core/datasets/test_create_dataset.py

Allow users to provide a text file for `rhv` rather than inputing them directly in config. Mainly helpful for OC20 if you want to filter on sids when there's 600k+.

Allow dataset subset to read in path to rhv

---

src/fairchem/applications/cattsunami/core/ocpneb.py

OCPNeb loading of fine tuned models is broken (#981) 
This can be reproduced when training, or finetuning any new model and passing it to OCPNeb. The reason here is that our loader uses the 'trainer' field in config to query the registry. 
However we populate the 'trainer' field with the task_name [here](https://github.com/FAIR-Chem/fairchem/blob/2e49a4efb5a8a5a175795f7898d16e3cbbfbdb71/src/fairchem/core/common/utils.py#L1079) and [here](https://github.com/FAIR-Chem/fairchem/blob/2e49a4efb5a8a5a175795f7898d16e3cbbfbdb71/src/fairchem/core/trainers/base_trainer.py#L128C14-L128C21)
To fix this we normally load models using OCPCalculator and pass the explicit trainer name in as an argument overriding the one present in the checkpoint. 
However OCPNeb does not have this option to pass in …

Fix OCPNeb trainer loading

---

configs/omat24/all/eqV2_153M.yml
configs/omat24/all/eqV2_31M.yml
configs/omat24/all/eqV2_86M.yml
configs/omat24/finetune/eqV2_153M_ft_salexmptrj.yml
configs/omat24/finetune/eqV2_31M_ft_salexmptrj.yml
configs/omat24/finetune/eqV2_86M_ft_salexmptrj.yml
configs/omat24/mptrj/eqV2_153M_dens_mptrj.yml
configs/omat24/mptrj/eqV2_31M_dens_mptrj.yml
configs/omat24/mptrj/eqV2_31M_mptrj.yml
configs/omat24/mptrj/eqV2_86M_dens_mptrj.yml

'mean_all' is no longer valid. 'mean' should be used now.

update reduction to mean in omat24 configs

---

packages/fairchem-core/pyproject.toml
src/fairchem/core/_cli_hydra.py

- Switch from arbitrary dict to separate dataclass
- add torchtnt to fairchem-core
Testing
- Checked 1 and 2 node jobs

Make slurm config separate class

---

src/fairchem/core/_cli_hydra.py
src/fairchem/core/components/runner.py

- Add a runner.state field to Job which will be used for auto-preemptions and manual resume of training states.
- pass full config to Runner instead of the partial config so it can be saved
- Move the job paths to a metadata field instead of using properties, this avoids having to instantiate the job config everytime you want the properties
Note This is for preemptions and manual resumes for runners, the state should be agnostic of whats underneath the runner (ie: a trainer or something else).
TODO: right now the state loading doesn't reload config from the saved config, we should change to this so that its strict and independent of the given config?

Modify runner and cli for state checkpointing

---

src/fairchem/core/common/data_parallel.py
src/fairchem/core/common/distutils.py

BalancedBatchSampler needs a device as input, this is not useful as the device should be inferred, make this optional and backwards compatible

Remove use of device from bbsampler

---

src/fairchem/core/_cli_hydra.py
tests/core/test_hydra_cli.py

- Fix bug where premption callback was not triggered
`job = executor.submit(runner_wrapper, cfg)` will end up losing the "checkpoint" callback because it its submitting the wrapper instead of the actual Checkpointable class, fixed this to:
`job = executor.submit(Submitit(), cfg)`
- (preemptions now working) https://fairwandb.org/fairchem/tnt_trainer/runs/202502-1500-2911-6246/workspace?nw=nwuserrgao
- Merge all the config init into a single function so it can be used for testing in dev

Fix preemption behavior and combine config init

---

packages/fairchem-core/pyproject.toml

Our pyproject.toml is incompatible with our tested version (torch==2.4.1). This small patch simply makes it to pyproject.toml will match any 2.4.x patch release.
Alternatively, we could update pyproject.toml to pin to `torch==2.4.1`.

Update pyproject to match torch 2.4.x patch versions

---

src/fairchem/core/datasets/ase_datasets.py

There is a very subtle issue when your config contains dataset paths like this:
```
src = [
"omat24/train/rattled-300",
"omat24/train/rattled-300-subsampled"
]
```
The metadata in this case will first sort paths and then concatenate them, in this example - `rattled-300` and then `rattled-300-subsampled` - https://github.com/FAIR-Chem/fairchem/blob/1573d44f85b32a8156df8faa403244ddd6198eec/src/fairchem/core/datasets/base_dataset.py#L85-L91
However, when constructing the db ids it first combines all lmdbs across all paths: https://github.com/FAIR-Chem/fairchem/blob/1573d44f85b32a8156df8faa403244ddd6198eec/src/fairchem/core/datasets/ase_datasets.py#L473-L480
In the example above this is problematic since now the sorted order looks as follows:
``` …
```

sort fix for multiple src

---

src/fairchem/core/common/relaxation/ase_utils.py

Having AMP on often leads to trouble during inference (rounding errors, energies not changing during relaxations, etc). This PR adds a flag to the calculator to force it off, and also defaults that to True. This is done using the trainer.scaling=None trick, but we could also overwrite the config if that was cleaner
Users who know what they're doing can use disable_amp=False, but the default for new users who aren't aware of issues should be AMP off.

Add disable_amp flag to OCP calculator

---

packages/env.cpu.yml
packages/env.gpu.yml
packages/fairchem-core/pyproject.toml
packages/requirements.txt

Our repo currently conflicts with orb (causing a problem in quacc). Lowering the version minimum to huggingface_hub to the minimum tested version (0.27.1) that is compatible with cached-path.

lower huggingfacehub version

---

.devcontainer/postCreateCommand.sh

The github codespace was missing the adsorbml requirements, including dscribe,x3dase,etc. This fixes that.

Fix github codespace install

---

src/fairchem/core/_cli_hydra.py
src/fairchem/core/common/utils.py
src/fairchem/core/components/runner.py

In the event of node failures, submitit would re-queue the job with the same submitted pickle it started with. This is problematic if the original pickle contained runner_state (ie: path to runner checkpoint to resume), it would repeatedly resume from the same checkpoint because the state is captured in the pickle. 
-> Here we manually remove the state path (not the most elegant way unfortunately) so that the runner_state is not propagated to future restarts
Extra cleanup changes:
* Add `is_preemption` flag to `save_state`, this allows the jobs to distinguish between when the submitit preemption callback is triggered and normal state saving (which only runs on master rank so it must be treated differently)
* Add return flag for `save_state` to indicate whether the save attempt was …

Remove runner_state_path from submission pickle

---

src/fairchem/core/models/pretrained_models.json

Fix a capitalization typo in the model registry names for OMAT potentials.

Fix typo in model registry names

---

tests/core/common/test_ase_calculator.py

If a PR is opened from a fork, the HF token won't be present as a secret to use for OMAT checkpoint tests. This PR skips the OMAT test if the token is not present in the huggingface_hub library.

only run tests if hf token is present

---

src/fairchem/core/_cli_hydra.py

Previously all ranks were modifying the pickle and can get into a race condition
Testing:

Move pickle modification into main rank behind barrier

---

src/fairchem/applications/AdsorbML/tutorials/adsorbml_walkthrough.ipynb

Previously, the Bulk and Adsorbate objects where passed directly when calling `os.makedir()`, which lead to errors with illegal characters. This proposes extracting the formulas and storing them as strings, then combining the strings when creating the directory where the trajectories from the `OCPCalculator `land.
Also the first import had a typo, missing an 'r'.

Minor fixes in tutorial notebook regarding directory naming and one typo

---

src/fairchem/core/trainers/base_trainer.py

When the logger is tensorboard, `self.config["logger"]` would be `str` instead of `dict`. This would cause:
```
[rank0]:   File "fairchem/src/fairchem/core/trainers/base_trainer.py", line 939, in _backward
[rank0]:     log_weight_frequency = self.config["logger"].get("log_weight_table", -1)
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: AttributeError: 'str' object has no attribute 'get'
```

Fix tensorboard logger

---

src/fairchem/core/_cli_hydra.py
src/fairchem/core/components/reducer.py
src/fairchem/core/components/runner.py
src/fairchem/core/components/utils.py

Add a `ManagedAttribute` descriptor as a formal way to write interfaces and allow runners to access a job config and reducers to access a job config and the calling runner config
* remove `initialize` method and use direct assignment with the  `ManagedAttribute`  descriptor

Config descriptors

---

docs/index.md

Fixes the name of the original location of this repo. Just in case anyone is trying to connect them.

Fix the original repo name in docs

---

.github/workflows/test.yml
tests/core/models/test_escn_compiles.py

- Add arg to log all test durations
- Disable escn compiles tests as they have suddenly dramatically increased in duration

Log test duration, disable ESCN compiles tests

---

src/fairchem/core/models/model_registry.py
src/fairchem/core/models/pretrained_models.json

Added eSEN-30M checkpoints that can be downloaded from hugging face, i.e.
```python
from fairchem.core import OCPCalculator
calc = OCPCalculator(model_name="eSEN-30M-OAM", cache_dir=".cache")
```

add eSEN model checkpoints to registry

---

src/fairchem/core/calculate/ase_calculator.py
src/fairchem/core/models/uma/escn_moe.py
tests/core/calculate/test_ase_calculator.py

Bug: https://github.com/facebookresearch/fairchem/issues/1218
The DatasetSpecificSingleHeadWrapper can't handle the UMATask enum that was introduced so it always created an empty mask and generated 0 predictions when enums were used.
* Added assertion to fail when the input dataset names aren't strict subset of what the model expects
* Cleaned up calculator to always translate UMATask -> str and can accept both as input

Fix bug when taskname is enum instead of str

---

src/fairchem/core/units/mlip_unit/api/inference.py

* TF32 is causing accuracy regressions during calculations like phonon benchmarks, turning this off by default

Dont use tf32 on by default

---

packages/fairchem-core/pyproject.toml

version `0.0.7` will return default values instead of failing if the code is running outside of a slurm cluster:
```
(base) luccab@luccab-mbp ~ % pip install clusterscope
Collecting clusterscope
Downloading clusterscope-0.0.7-py3-none-any.whl (10 kB)
Installing collected packages: clusterscope
Successfully installed clusterscope-0.0.7
(base) luccab@luccab-mbp ~ % python
Python 3.11.4 (main, Jul  5 2023, 08:40:20) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import clusterscope
>>> clusterscope.slurm_version()
(0,)
>>> clusterscope.cluster()
'local-node'
```

upgrading clusterscope

---

packages/fairchem-core/pyproject.toml
tests/requirements.txt

Tests broken. One obvious change is that LMDB went from 1.6.2 to 1.7.1. This is a test PR to see if that fixes things

revert lmdb version

---

.github/workflows/build_docs.yml
.github/workflows/test.yml

test and build_docs workflows are called from other workflows in the release pipeline. Adding workflow_call triggers to each so that they can be run correctly.

Allow test and build_docs workflows to run on workflow_call

---

configs/uma/finetune/data/uma_conserving_data_task_energy.yaml
configs/uma/finetune/data/uma_conserving_data_task_energy_force.yaml
configs/uma/finetune/data/uma_conserving_data_task_energy_force_stress.yaml
src/fairchem/core/datasets/collaters/mt_collater.py
src/fairchem/core/scripts/create_uma_finetune_dataset.py
src/fairchem/core/units/mlip_unit/mlip_unit.py
tests/core/scripts/test_create_finetune_dataset.py

This address https://github.com/facebookresearch/fairchem/issues/1329 and https://github.com/facebookresearch/fairchem/issues/1386
The current mlip_unit was designed such that only tasks trained can be outputs during inference time. However, for conservative models, we want to allow predictions of forces and stress on energy only training for example. This PR adds a "inference_only" tag to `Tasks` which indicates to the training code to ignore these tasks during training and then can be used for inference. 
* manual verification
* pytest tests/core/scripts/test_create_finetune_dataset.py

Add inference-only tasks to allow predicting on tasks not trained on

---

src/fairchem/core/models/uma/escn_md.py
tests/core/units/mlip_unit/test_emeddings.py

This PR adds embeddings to be returned through the EFS head. These embeddings can then be piped up through predictor by adding an additional task to make it compatible with collater.

[ BE ] add user accessible embeddings

---

src/fairchem/core/_cli.py
src/fairchem/core/calculate/ase_calculator.py
src/fairchem/core/common/utils.py
src/fairchem/core/units/mlip_unit/api/inference.py
src/fairchem/core/units/mlip_unit/mlip_unit.py

We currently implement string enums using `MyEnum(str, Enum)`. The behavior of `MyEnum` is different in python 3.10 and >=3.11 since `enum.StrEnum` was added instead.
This PR attempts to import `StrEnum` and if not falls back on using (str, Enum). Doing so ensures the same behavior in python >=3.10

StrEnum backwards compatibility
